#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Chunks
categories: attempts
---
#+END_EXPORT

** Chunks
   No, not the vomit kind. Okay maybe.

   As I've prattled on about before, human beings spend a lot of time
   either /a)/ subconsciously sorting things into categories (right,
   wrong, dark, light, progress, regress, etc) or /b)/ consciously
   deciding what categories things go in, with an awareness that the
   categories are fuzzy and the points don't matter and live from new
   york it's saturday night. You can try, but you can't escape it, and
   in this weird wide world containing the internet, where we can be
   exposed to any ideas that we choose, and in the privacy of our own
   homes make decisions about how we are going to engage with those
   ideas, we need to hone our metacognitive
   skills. Meta-metacognitive? Idk. You get the
   concept. Concept. Concept. Say it three times and turn in a
   circle. Concepts are... what? Ideas? Beliefs? Grouping of those
   things?

   Categories are tangent to what I want to talk about, concepts are
   adjacent to it: the bit I need is the psychological concept of the
   [[https://en.wikipedia.org/wiki/Chunking_(psychology)][chunk]]. Chunking, and the paper that first synthesized the concept,
   "/The Magical Number Seven, Plus or Minus Two: Some Limits on Our
   Capacity for Processing Information/," are such cultural staples
   that any writing on the topic is bound to seem trite, but here we
   go. The important bit is this:

   #+BEGIN_QUOTE
   A chunk is defined as a familiar collection of more elementary units
   that have been inter-associated and stored in memory repeatedly and
   act as a coherent, integrated group when retrieved. -- Wikipedia

   -- Tulving, E., & Craik, F
   #+END_QUOTE

   Chunks are psychic objects, the basic building blocks with which we
   assemble our working memory, and thereby our thought. It doesn't
   matter if a chunk is a single binary digit, or a re-coding into
   higher space therefrom, or the entire idea of "whale", or "pizza",
   or "nazism", or "blog." Our largest chunks confine our largest
   thoughts. Chunks are how we contemplate the world. Refinement of
   our chunks is refinement of our consciousness. This is how
   "chunking" can be tidily inverted, now a big glass bowl
   encompassing some of the more political and philosophical things
   that we can discuss.

   Chunking is sublimely underrated as a tool for more effective
   understandings of consciousness and the workings therein.

   I'm aware of one other work on this topic, and a neat, Maria Popova
   summary is available [[https://www.brainpickings.org/2012/09/04/the-ravenous-brain-daniel-bor/][here]]. I haven't read the book, but it
   certainly seems interesting, and a definitively more scientific
   description than the allusions, metaphors, and inanity offered
   herein.

   To be aware that chunking is necessary, chunking is largely
   unconscious, chunking is how we are socialized, and chunking is the
   product of our own personal investigation, is to be aware of the
   forces that divide, and the forces that unite us in
   humanity. Education can become "tools to encourage re-chunking."
   Drugs "encourage the rapid disintegration of chunks." Inspiration
   contains the "rapid expansion of a chunk to contain new contexts."

   It's criminally easy to abuse the metaphor (chunk) of chunks, and
   it sounds insane, which is why I've tried to explain these things
   to exactly zero people.

*** Ontology
    Ontology is concerned with reality and its categories. It's one
    big arm of metaphysics (that statement itself being an ontological
    assessment), and it's everywhere. You just have to know where to
    look.

    Reasoning about the nature of reality, about the fundamental
    properties of a thing, about what markers are needed to fill the
    requirements of an /identity/, questions of /self/ versus /other/
    and /in-group/ versus /out-group/, these are actually (and often
    unconsciously) works of ontology.

    What the nonsensical introduction was getting at, then, is that,
    like it or not, we spend an inordinate amount of time doing
    (committing?) /ontology/.

    Ontology, neurologically speaking, could just be the study of
    chunks. I'm willing to bet enough on this to type words into a
    computer, so I'd say I'm pretty sure. Since ontology is focused on
    the boundaries of things, and chunks are the psychic set of
    boundaries between concepts, objects, and more, chunks are a
    superset of ontology.

    Ontology is also in charge of the categories themselves. You
    cannot determine what category an item belongs to without first
    having a list of categories. Categories are established through
    the process of comparison that identifies "like" things.

    When we say that one thing is like another thing, we've made a
    metaphor, and we're thinking analogically. Categorization /is/
    metaphorization.

*** Semantics
    I made a groaner the other night, realizing that semantics is
    metaphor without hyperbole -- the unit metaphor is straightforward
    and useful. Of course, if there are unit metaphors, then maybe
    there are scalar metaphors, or metaphor transforms. Who knows?

    A chair is a construction of wood, cushion, or otherwise, that
    facilitates sitting. A stool is like a chair, but dumber. You
    prefer stools? Psychopath.

    Her eyes were cerulean kiddie pools. Her eyes were bubbles of
    fluid for focusing light on a sensor. It's not pretty, but it gets
    the job done.

    The very descriptive act is one of comparison, the decision that
    things are like other things.

    #+BEGIN_QUOTE
     We get it poets: things are like other things

     -- [[https://twitter.com/shutupmikeginn/status/508799244778889216][Mike "Writer" Ginn]]
    #+END_QUOTE

    #+BEGIN_QUOTE
    also, comedians / yes... comedians are like poets

    -- in the @ replies
    #+END_QUOTE

    Funny joke! Creative, collective definition is all of our
    jobs... some people are just more aware of it than others.

    Semantics is fundamentally description, description is
    fundamentally metaphor, and metaphor fundamentally chunking. We're
    captive on a carousel of time. Every time I say fundamentally I
    draw a big red circle around my categorization impulse and further
    entrench this stupid chunking idea.

    As we unroll semantics and look more deeply at what words and
    definitions /are/, [[http://psycnet.apa.org/journals/xlm/16/5/852.html][semantic]] [[https://en.wikipedia.org/wiki/Semantic_satiation][satiation]] seems to wink wink nudge
    nudge at deep neurological implications. When we use a word into
    total exhaustion we temporarily rob our mind of the word's
    usefulness. We lose its /meaning/, its /chunk/, its metaphorical,
    ontological /way of being/. The hole it leaves is terrifying. How
    did you spend so long with the sense of this thing, only to lose
    it into the ether? Even more terrifyingly, related concepts are
    /also/ weakened. If we lose our "table" chunk, we weaken our
    "desk" chunk. The miasma of an idea, the metaphorical and physical
    relatedness of the building blocks of our consciousness, can be
    partially dissolved by the words we choose to assign them.

    Is this why repeated chants channel such great power? Is it that
    filling the mind with (what are now) nonsense syllables clears
    your pool of conscious thought and makes space for something less
    verbal? Something closer to god?

    Is the inverse phenomena of [[https://en.wikipedia.org/wiki/Glossolalia][glossolalia]] just that? Nonsense
    syllables of a cleared mind? Is glossolalic interpretation hearing
    nonsense and understanding, while semantic satiation is hearing
    real words and failing?

*** Jargon
    Jargon seems like an arbitrary barrier to entry for any given
    academic field. It's arcane, it's needlessly complicated, it's
    elitist, and it seems, from an outsider's perspective, that
    regular ol' words will do just fine, thank you.

    People "[[https://en.wikipedia.org/wiki/Ontology_engineering][in the know]]" already know that the entirety of a field's
    jargon is its "ontology." When there was a push for the "Semantic
    Web," ontology was also the chunk they used to represent domain
    knowledge, saying, in one common example, that a book site would
    use "author" where a more general site might use "creator." Author
    is more descriptive than creator. It captures more information
    --more context-- than creator, and represents a larger chunk.

    Jargon, domain knowledge, ontology, chunks-- these things capture
    information much more complex than simple words, their phonemes,
    or even their definitions. When you enter a specialized field
    these chunks contain increasingly large amounts of
    information. Eventually some information is added that causes one
    chunk to diverge from a previous version. To distinguish new
    chunks from older chunks, new vocabulary is invented.

    It is when working with these complex ideas that jargon becomes
    desirable, since specialized vocabulary is imbued with the
    potentiality of triggering chunk loads, allowing the reader or
    thinker to access larger and larger pieces of information
    simultaneously.

    The cargo-cultist possesses the half of a chunk that is
    superficially available, without bothering to (or knowing enough
    to) ferret out more deep and nuanced meaning. It is always the job
    of philosophers (and /Doctors of Philosophy in ______/) to
    spend enough time with the meanings of things that the whole
    chunks are uncovered and the full context made apparent once
    again.

*** Vocabulary Words / Foreign Words
    Sometimes true meanings are obliterated by our proximity to
    them.

    Boredom is a powerful chunk containing dissatisfaction with the
    state of reality and the urge to escape it. It is listlessness and
    aimlessness and existential anxiety. How often do we unpack
    boredom? When we speak "boredom" do we expect our listeners to
    unpack the chunk and actually feel something? Maybe it's easier to
    use a word that makes us work a little harder, allowing us to
    become aware of its subtlety as we think. How about /ennui/?
    /Ennui/ is beautiful, and for me has always captured the more
    "real" bits of boredom. I'm not bored of an activity. Activities
    are easy to find. Maybe I'm bored of /all/ of this.

    Maybe /ennui/ is already too loaded, "loading" in this context is
    a flattening of our chunks so that they look, from the outside,
    like things much less complex than they are, removing the
    intensity of meaning in a hedonic treadmill. Thoughts can only
    move us for so long. Cargo cults are shallow, like the
    understanding gleaned from [[post:2017-03-01-travel-blog.org][visiting]] a place, but never living
    there.

    Other times, however, a language is entirely missing a word to
    capture a particular chunk. It somewhat bothers me when I see
    "untranslatable words" or things of that ilk, because of course
    english is infinitely expressive, and what they mean is that there
    is no single word translation. But, when brevity is desired or you
    would like to instantly trigger the loading of a particular,
    /huge/ chunk, using a foreign word is infinitely more
    efficient. At this point foreign words become jargon for our
    everyday experience.  /Fremdschämen/ from German, /Saudade/ from
    Portuguese, the /Vus/ from French. These words have no "simple"
    translation, but immediately and thoroughly capture potent
    chunkcepts. I've wept over beautiful words. This is okay. I'm
    fine.

*** Genius and a few good chunks
    I read somewhere [citation needed(probably from inside the
    rationality-web)] that even the most genius people have only a few
    good tricks: a set of mental tools by which they approach every
    problem. If their tricks don't work, maybe file the problem away
    for a while until new tricks can be learned or new information can
    be gleaned about the problem itself. Being productive dictates
    shelving unpleasant problems from time to time.

    Anyway, the tricks are reductions, incarnations of the analogical thinking
    that ontology empowers. The question is always 'is this problem
    "like" another problem?' Is there an approach I know that works
    here, too? Are the logical threads the same?  Are the crossings of
    rope unique to this problem not so unique after all?  Is it the
    same knot in a different context? I've wept over the same knots in
    different contexts. This is okay. I'm fine.

    Computicians[sic] are already directly aware of these workings:
    progress in this field almost always occurs via the reduction of
    one problem to another -- what once seemed intractable now
    accessible through the arcane machinations and mathematics of
    yore. If one problem is reducible to another, it is already
    solved.

    As we've seen, most work is just figuring out what things are like
    other things anyway. Poetry. /Poiesis/. Creation.

*** Personal Revelation as "new chunk"
    /ker-chunk!/

    That's the sound of a new metaphor falling into place, your new
    analogy another brick in the wall of Knowledge. You've compared
    two things, and now you understand. This is the nature of
    knowledge, that text is nothing without context.

    By comparing two things, you've encouraged their chunks to merge,
    you're blurring the boundary between one thing and another. We can
    say, when speaking analogically, "of course I don't /literally/
    mean that one thing is like another, but of course it is. It is if
    our unit metaphors are tight enough.

    The moment of epiphany is a spectacular subduction of one chunk by
    another, the sublime rumblings of expanding definitions and better
    comparisons, stories to tell yourself that feel more whole, and a
    better angle on the facts.

    Epiphany feels so good because your brain finally knows where to
    put things. What a relief.

*** Explainers, and encouraging others to "Get It"
    If this blog has a purpose, it is to realign your perception of
    the world to be just a little bit more similar to my own. This is
    often the goal of "explainers," articles, videos, books, that are
    an attempt by one human to explain something to another. Sometimes
    this works well, and is necessary, like apprenticeships in trades
    and membership in dojos for the physical arts. Sometimes it seems
    to fall flat, like in the case of personal advice columns and
    self-help books.

    When we explain, if we feel frustration at someone else not
    "getting it" they either haven't heard us correctly, or their
    information is chunked such that whatever new info you've provided
    is being sorted into a pile that might not even exist in your
    brain.

    Sometimes these piles can be the source of our greatest
    naïvetés. Progress -- new, better perspectives, are available to
    those who are just now in the process of building up their chunks,
    and much can be gained by questioning the validity of some of our
    more "fundamental" chunks. Gender is a good chunk to break
    apart. Gender contains a lot of information, and has historically
    been very useful. But gender chunks contain humans, and humans are
    tricky.

    In this case we may do well to chunk less information in gender,
    and work more slowly out from there.

    Or maybe we would do better to chunk /more/ information with
    gender, including more information about ambiguity, spectrum, and
    complexity. In this case we must still make sure we don't become
    desensitized to meaning-- we must unpack gender every time we
    speak of it.

    Maybe the real trick is only to use foreign words for gender.

    I've gotten derailed. I hope when you pick up your chunks you find
    them healthy and whole.
