#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Travel Blog
categories: attempts
---
#+END_EXPORT
** Travel Blog
You desire to live in what is new and intense. To save, at any cost,
those poor moments scattered haphazardly over your lifetime whose
vividness begs to be a part of your eternal memory. You skillfully
oblige these moments, using mnemonic tools to aid in the remembrance,
even reliving the moments publicly with blogs and pictures, hoping to
bring others into the fantasy and shared memory. One of the fastest
routes to vividness is a new place, a far flung destination. One of
the other fastest routes is drugs.

Most people who take drugs don't record those experiences for other
people to see. Drugs are stigmatized such that even well-constructed
stories about meaningful drug experiences are likely to be dismissed
casually. The newness of those moments is not well preserved.

For travel, on the other hand, the ubiquity of the travel blog is
proof positive. Personal travel journals -- another incarnation. New
places connect us to our senses, and allow the moments we experience
to break the translucent curtain of the everday. Go for a bar crawl at
home and it's fun. Go for a bar crawl in a new city and it's
/Memorable/. This is why moving to a new place can be cathartic, and
why moving to a new city and failing to find your footing quickly can
be devastating. You imprint on new places. Those first hours are
amplified, those first few days either totally magical or a total
disaster. Often, our favorite places are in far-flung cities, not in
our own back yard.

I was overcome with sadness when I realized that I'd lost my chance to
intentionally engage with the newness of Minneapolis. I'd lost my
opportunity to experience travel's vividness in my own town. I spent a
year with a car commute and a Netflix subscription. I spent a year too
socially anxious to do things on my own. Depression had claimed my
opportunity, and there was nothing I could do to get it back. I felt
none of the vividness and salience that I had hoped the move would
bring. I felt only frustration.

In the many days that have followed, salience, and our ability to
manufacture or enhance it, have been frequent topics for my own
investigation.

This is a travel blog that's not about newness. It's about
familiarity, finding vividness and salience in the stretch of 1.25
miles that I've walked over 1000 times, and the time that I sacrifice
to the street each morning and afternoon.

*** The Walk
I spend 6% of my time walking to work. Besides sleeping and working,
it's the single activity that I spend the most time doing. All that
time is "wasted," too. I can't accomplish anything during those hours
but the movement of my body and the perusal of my own thought. I've
walked the same walk every day for more than two years. I could halve
my commute by biking or driving. A diligent optimizer would eliminate
this walk at the first possible opportunity. My motion muda is off the
charts.

Walking takes place at an agonizingly slow, sweet pace. Cars rush by
you. /Bikes/ rush by you. */Runners/* rush by you. Your pace is one by
which you may admire the cracks in the sidewalk, find some funny trash
in a gutter, and fully take in the impromptu art of the city.

#+BEGIN_QUOTE
"I tell you, we are here on Earth to fart around, and don't let anyone
tell you different."

-- Kurt Vonnegut
#+END_QUOTE

The roads you travel are residential and filled with people. There's a
guy walking down the middle of the street who careens towards you and
mumbles something about "Adderalls", and a guy dressed in paramilitary
gear and operating an electric lawn mower every Friday morning at
11am, and a lady with two dogs, large as bears, that crosses the
street so you don't have to deal with them. There's a guy that works
as a contractor during the summer but really has a hard time finding
any work during the winter, and it's cold, and he may ask you for some
money.

You recognize people who don't recognize you, and if you're
adventurous enough you may call their name and scare the living shit
out of them. Sometimes you walk your route in the opposite direction
of a stranger so many times that you're sure they recognize your face
now, but some nebulous city etiquette prevents you from trying to make
that connection. Ditto the lady who served you pizza earlier in the
afternoon. The guy in paramilitary gear eventually starts waving
hello, though.

Sometimes, the apartment building you've walked by 500 times is
suddenly on fire, and over the next 500 walks you watch the damage be
slowly undone. No windows, blackened interior. Boards on the
windows. Painted boards on the windows. Windows for windows
again. Painted interior. The building nursed slowly back to health.

You cross an interstate bridge, and the cars rushing below take your
breath away. Tires on the road have different tones, and big trucks
are always carrying a whooshing sucking vortex that's not on the
manifest. It's a scary bridge. The concrete develops cracks on its
surface that are patched, slipshod, whenever the snow melts. Gray
patches of paint are the drab ghosts graffiti, their mostly positive
messages the victims of the rule of law.

*** First Dhyāna
Slow down. Don't linger on a thought. Don't even let a sentence of
your own cogitation reach completion. Become a vessel for your senses,
aware of your breathing, your repetitive footfall, and the vast
soundscape that has unfolded around you. Feel the cool air on your
face, and the crick in your knee that aches a little when you swing
your leg forward but not when you swing it back. Notice how your
third toe on your right foot rubs a little bit on the inside of your
shoe, and how your shoulders feel strained by the weight of your
backpack. Collect these sensations easily, without judgment, and
eventually, paradoxically, they fade away. Or rather they fade /into/
the moment and become inseparable from it.

What results is a sensational moment with sweeping cinematography and
crystal-clear, larger-than-life sound engineering. The film, shot with
two high resolution cameras, makes great use of the third
dimension. The script, while not exactly an intellectual /tour de
force/, is distinctly and beautifully human.

Now linger in this moment. Develop the plot at your own
speed. Probably there is no plot. The moment is there for its own
purpose. [[https://www.youtube.com/watch?v=osrvO9Q3PtI][/Ambedo/]]. The opportunity is there to realize that you've
felt this way before. Maybe in the fog on a lonely dock, or when
focused on a particularly meticulous task that you enjoy, or
hand-in-hand with your true love, or in a silent moment on a weird
drug trip, or even when watching a movie or enjoying a meal alone. Who
knows.

What matters is that you now know that you have access to these
moments spontaneously, through triggering events, and on demand,
through walking reflection. What are they? You remember them, that's
clear, but they lack the intensity, the multiplicative elements that
demarcate your other memories. Not a first, not a last, just an
everyday experience exploded in importance by some unknown mechanism
deep in your brain.

They're the moments that haven't been crushed by the moments that
follow. Vividness. Salience. Salience and easy, quiet bliss.

*** The Visionary Experience
Aldous Huxley described something he called the "visionary
experience," a sort of rapture that overcomes the artist, the veil
that time has woven removed, the world impossibly more real than it
ever was before, the details patterned so exceptionally upon it now
made clear.  Similarly, positive psychologists think about "flow," a
human state where time dilates and the self dissolves into the task at
hand. During the throes of early love, the edges of our experience
feel on fire, moments stretch into infinity, and we're engrossed in
the task of creating passion and bliss for ourselves and another.

When we walk to work, we can commingle with our senses in a way that
clarifies thought, amplifies detail, and stokes meaning. Love even
makes this commingling easier-- nostalgia's sepia tendrils are ever
more apparent to us when we're used to the feeling. The crystalline
salience of a moment becoming a memory, of immediate meaning, is more
easily observed when we have a ready comparison to something in our
everyday life.

I've coaxed these experiences under the single umbrella of
salience. Not that they are the same phenomena, but that they possess
enough of the same elements that they may have a common
ancestor. Genus bliss, maybe. Simply knowing that some feelings point
to, or spawn from, similar places has helped me harness each one
individually. The possibilities for using that feeling, that a moment
has meaning, are nearly endless.

*** Deep or Wide
The poet Michael Longley has [[https://soundcloud.com/onbeing/michael-longley-the-vitality-of-ordinary-things#t=34:08][implied]] that although travel broadens the
mind, it also /shallows/ the mind somewhat, the antidote to which, he
goes on to say, may be going back to the same place, over and over, in
a curious and devoted way. The true appreciation of that which is now
ordinary can become our greatest tool for deepening ourselves and our
understanding of the world that we have inherited.

It makes intuitive sense that depth comes from repeated exposure, and
breadth from newness, those unrepeatable one-time experiences and
adventures. We carve outward at the boundaries of our own
consciousness, and this is fast and exciting, but the rubble falls
unceremoniously into our once still pond. The process of removing it,
dredging the depths and deepening the pond again is a long and
laborious process. When we come into contact with something new and
exciting it becomes a trap for our thoughts. It manifests as lust or
obsession, fills our conversations, and makes the "real world" seem
drab by comparison. With repetition instead we are blessed by the
opportunity to fight the drab and to make our own meaning.

Practice, refinement, these are the same neural slight of hand. When
we learn new things, they excite and titillate, but meaning building
and true understanding come with curious and informed repetition. It's
become intellectual vogue to quote Feynman and talk about "cargo
cultism" when going through the motions and expecting results without
understanding the deeper reasons. Repetition, curiosity, and devotion
to craft, coupled with the guiding hand of someone who has already
found the way, are the salve to this guileless performance.

When I started walking to work, after having commuted by car for the
last year, I wanted to know how this waste of time was any
different. I wanted to know how a whole hour of my day could be spent
better. I wanted to find purpose in the small things. Even if work was
hard, I wanted the journey there to be meaningful, and if I couldn't
find meaning immediately, I wanted to practice until I could.

With that in mind, and with the lessons of various podcasters and
[[post:2017-02-13-why-to-blog.org][bloggers]] in my fore-brain, I set to work.

Not that the oft-cited 10,000 hours of practice to mastery is correct,
but I often ask myself what I've /already/ spent 10,000 hours
practicing. What am I already a master of?  Anything?

I'm not there yet with my walking routine. I've only walked to work
1000 times.

*** There's More to This
I want to set this blog loose on the world, so I'm ending
here.
