#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Glomular Outlook
categories: attempts
---
#+END_EXPORT

** Glomular Outlook
I can't say I'm into this.

We're forced to create a junk drawer for any of our beliefs that don't
fit into any of our currently available schema. This says nothing of
the individual qualia of which our beliefs are composed, which also
may need a junk drawer within our thoroughly schematic beliefs.

The icky sticky of life happens in these junk drawers. There are no
good answers. If you're lucky you've managed to sort the junk into
a few jars. Maybe "important" and "maybe important later who
knows."

If you're unlucky there's stuff in those drawers that you should
have categorized and dealt with ages ago. Those rubber bands? Don't
you have a spot somewhere in your office supplies where you are
keeping other miscellaneous fasteners? Shouldn't the playing cards
be next to the board games, and the flashlight be in a toolbox?

Maybe you just need to expand your concept of junk and get another
junk drawer, since now that you think about it "miscellaneous
fastener" is kinda broad, and the twist-ties seem out of place by
the stapler. The flashlight, similarly, is only as much of a "tool"
as your other electronic gadgets. What the hell?

Whenever I pack for vacations and parties I start putting
everything into bags until I literally pack my whole apartment
away. It's all "necessary," isn't it?

More abstractly, what do you do in your free time? Is it really free?
After you've intentionally structured that time isn't it taken up?
Maybe what I mean by "free time" is vacation. What do you do on
vacation? I don't mean going somewhere. That's too much work. I think
I mean "staycation." Or leisure? Leisure. /I/ stare at the
ceiling. Works of narrative fiction are too exhausting, too consuming,
too imagination limiting.

It's an up-hill ontological battle with everyday things, everyday
/beliefs/, everyday subjective experiences. It's not far from these
qualia to the big-ticket items, the important things that everyone
wants you to think about.

"Wait a second," you say, nationalism forms a backbone for socialism
*and* fascism? No way. Those anarchists over there believe that
violence can be justified for the right purposes? Doesn't that sound
familiar?  Historically some of the most vocal proponents for
anarchism have eventually /become/ fascists? Isn't that weird?  Your
anarchism isn't intersectional? Stateless palingenetic
ultranationalism?? Jesus fucking Christ. Proponents of liberal
democracy are racists, right? What about democratic socialism?  Maybe
that's okay. How do we get the right people in power? Rising up and
killing the ruling class is what happened in Rwanda. They were touched
by colonialism. So were we. What are the only places I can think of
that weren't colonized? Somalia. Antarctica? No, wait, Antarctica
counts. Technically everywhere there are humans was colonized, so I
guess I really mean colonized more than once. Maybe Antarctica doesn't
count after all.

Do we trust ourselves to draw solid lines between beliefs? Have we
been so conditioned to believe that we can discern, without doubt,
what values are better than others?  Like the Years of Lead, do we
believe ourselves so different from those that oppose us? Are we
willing to raise the rhetoric and fight back? Are we willing to whip
ourselves into a fervor and froth at the mouth and spittle on our
enemies until they back down?

Inspiring doubt in your beliefs is a key marketing tactic that's
used to sell you software, cars, gadgets, and other "solutions" to
quotidian hardship. Fear, uncertainty, and doubt. Volatility,
uncertainty, complexity, and ambiguity. I'm sorry, can I stop you?
The very idea of "quotidian hardship" is very "-ist," and a lot of
them. Disinformation, undermining the very quality of "realness"
that defines reality(reality?), is the tactic of the Kremlin. Don't
forget, there was no attempt at communism or equality. Don't
forget, there was no attempt at democracy or equality.

This is all so confusing. I'm not making any sense. I need someone
to tell me what to believe. What else could there be? Telling
people how to live their lives has worked so well in the
past. Drugs are gone and companies pay their taxes. These issues
effect real people, they're not personal decisions, they're
decisions we make for the common good. Alcoholism hurts people, and
not just the people that are alcoholics. That's why we passed a
constitutional amendment banning drinking. It's reflective of our
values.

Our large scale efforts to produce educated young people that
believe what we want them to believe have largely failed, except at
the university level. Do we continue to expand the number of people
going to college in order to fix this? Women are 60% of college
graduates, so maybe we need some outreach to young men.

It really is too bad that we can't help young men without helping
young men.

I'm sorry, can we reel this back a little bit? Education was a key
plank of the KKK's party platform, and at one point they launched
an initiative to buy up universities across the country. I'm
uncomfortable with this. Universities as indoctrination factories
are just... hm.

Maybe instead of higher education for all we should be looking to
limit "alternative" educations for the young. Homeschooling, for the
most part, seems like no good. I'm just spitballing. What about
christian radio? Seems unnecessary. Well, okay, but a bidding war
between NPR and christian radio stations has increased the payout of
selling a radio frequency in the US, and generally the victim is
alternative music on the airwaves. Great.

That's like two things. Lol. Maybe there's not a lot of alternative
education out there after all.

Maybe we're okay. Maybe there is no solution. Maybe there's just a
powerful law of averages at play that we can accept.

Accept?? Blind acceptance of the norm is tyranny. Tyranny that
/YOU/ are /IMPOSING/ on other people. What is wrong with you? We
/need/ a path forward. We need to believe that our contributions to
this world mean something and affect someone. We need to believe
that we can force someone's hand, and that the entirety of
non-domination requires it. Who has the power, if it can so easily
be taken away?

Blind acceptance of normies is also tyranny. Make those shits
uncomfortable.

When my shits are uncomfortable I really sit back and think about
my life and how much evil I must have done to deserve them. That's
the goal.

So where do I even begin? I think that this is a war for our souls,
if we have them.

*** Syncretization
We have to believe something. The alternative is too dangerous. I
won't elaborate on that.

I don't trust anyone who thinks that their beliefs are fully in line
with an established narrative. If you can think that then you haven't
thought enough. As you add preconditions theories becomes less and
less likely. What are the chances that all of the preconditions of a
social theory are well met? Perfect markets obey mathematical
rules. Markets are rarely perfect. [[https://www.nytimes.com/2017/02/21/business/economy/kenneth-arrow-dead-nobel-laureate-in-economics.html?_r=0][Smart people]] are okay with this
uncertainty. Can you be? This is actually, exactly where the fun stuff
begins. If you can accept that many social theories are equally
unlikely, you can begin to synthesize something like truly personal
socio-political beliefs, untethered from the whims of some other
person's pet theory. Marx lived and thought in a world that had a
particular, confounding set of cultural inputs. So did Mill. So did
Sontag, so does Hakim Bey, so does Ta-Nehesi Coates, so does Judith
Butler.

So does Mencius Moldbug?

So do you. The faster that you can be okay with being wrong, the
better chance you have of finding something worthwhile.

So what do you believe? Where did these ideas come from? Do you
remember? Can you find the sources of bias in your own thought,
the distortions in the lens of your perception? And if you can do
that, can you spot the distortions in the lenses of others?

Keep these things in mind and assemble your beliefs. Stand by the
important ones, the ones that you couldn't live without. If you had to
leave, NOW, and bring with you only a [[http://www.merlinmann.com/roderick/ep-133-secret-pope-songs.html][small bag]] of your most important
ideas, what would they be? How big, exactly, is your small bag? Can
you fit a few more things? How about fewer? They'd fit more
comfortably that way. Traveling without supplies really is too
[[https://meaningness.com/nihilism][dangerous]].

It's always up to you. You start with a [[post:2017-04-19-chunks.org][form]], a natural container for
your ideas that is the result of your genetics, upbringing, and
acculturation. From there you aggregate beliefs as they feel good, and
/make sense/. In art, this process of building out intuitively from
form and letting each piece find its home instinctually is
/bricolage/. Maybe the endeavor to be better /bricoleurs/ and
/bricoleusses/ of our own consciousness is a worthy one. As your own
ideas emerge, naturally, from the pile of available beliefs, something
beautiful is created. Something that doesn't need validation from a
wider audience, because /you know/ no one else can agree with you. You
can grind your lens down a little where it needs, understanding that
the image it projects is still not reality, but a more personal vision
of truth.

*** Skepticism
To embrace rationality is to be somewhere along the way to developing
personal, unique, syncretic beliefs. To be rational requires changing
your assessments when new evidence is presented.

This process of updating your personal beliefs based on new
information is narrative-shaking; understanding that there are more
than two sides to every story can facilitate empathy and productive
understanding with even the most dissimilar people. Irritability with
others' confused approach to the world is also normal, if you're an
asshole.

Things are complicated. Not only are other people wrong, you are
wrong too.

[[https://arxiv.org/abs/1003.2688][Level 4 Uncertainty]] permeates every level of our life, and
therefore the models that we use to understand the world must rely
on a complex meta-understanding of multiple models that produce
inputs somewhat unpredictably. Like Lo and Mueller say, if we want
our world to be model-able mathematically, "we must resign
ourselves to models with stochastic parameters or multiple regimes
that may not embody universal truth, but are merely useful."

#+BEGIN_QUOTE
"If people do not believe that mathematics is simple, it is only
because they do not realize how complicated life is."

-- John von Neumann
#+End_QUOTE

That's an end-goal, then. A path forward. An understanding that in
order to have "useful" beliefs, we must give up all pretension of them
embodying universal truths. And if our beliefs have very little hope
of capturing universal truths then we may as well allow ourselves to
work with many different models of reality fluidly, collecting the
best bits of the best thought for ourselves, and sloughing them off as
they are no longer useful.

This begins to look a lot like a mathy version of David Chapman's
[[https://meaningness.com/preview-eternalism-and-nihilism][Complete Stance]], which captures the limits of rationality, but admits
its utility at the same time. (side note, "Meaningness" should be
required reading for anyone that wants to exist on the internet. Just
don't get any ideas and start blogging like me, I need a niche here)

The Complete Stance, which is something like post-positivism for
spirituality, is something that we all engage with. It is the
recognition that there are no solid meanings handed down from above,
but that things are meaningful, nonetheless. We can find -- or attempt
to find -- the patterns that define reality, but reality's chaotic
nebulosity resists "universal truth."

*** Amathia
There is always a certain [[http://www.iep.utm.edu/arendt/#H6][banality]] to evil. An innocuous, unthinking
progression from one action to the next, not in /spite/ of others'
human dignity, but merely without regard for it.

The mechanism of this unthinking is Amathia, which Hannah Arendt
(linked above) and more recently youtuber Gary Edwards single
out as the core personal vice of totalitarians the world over.

If the way forward is to abandon the idea that beliefs can embody
universal truths, then Amathia is the way backward. It is the
unwillingness to think beyond your own position, the stubborn
foolishness of believing that the knowledge that you have is enough;
that your personal truths constitute universal ones, that the lens by
which you have already begun to categorize the world is clear and
unbent.

So often it is not ideas that are dangerous, it is the people that
hold them, and the fervor by which they will throw themselves at
opposing ideas in arenas other than the circle-jerk of academia; the
problem is not the ideas, the problem is the adherents, those
hell-bent on thinking nothing other than what they've already
thought. The paranoid, the faithful, the driven. Anti-social ambition
cum wide scale misanthropy.

Maybe the best thing in general, then, is to reduce fervor. Dedicate
passion to more interesting human pursuits than politics and religion.

It's hard, if not impossible, to get drawn up by Amathia if your
beliefs are a conscious collection of the best bits of every system
that you can find. If your skeptical ideological syncretion becomes an
end-goal, you've padded yourself against the assault of assumption.

Your ideas will be complicit in gentle bad, since no one is safe from
that, but you won't tolerate evil. You're too smart for evil. Maybe.

At least that's the idea. If you syncrete a little harder and get
content with your new beliefs you may not catch yourself slipping into
evil. Evil is the world's worst accident, the existential equivalent
of wetting the bed. You don't want that. You want to recognize the
tickle as you dream about your porcelain heaven, and you want to get
yourself to the existential washing-up room as fast as humanly possible.

So, that drawer containing your political belief... are you sure it's
the right one? Are you sure you can't get down in there and shuffle
things around at the ontological level? Are you sure that the edges of
your belief aren't fuzzy enough to disqualify it from any of the
drawers?  Are you sure you aren't sleep-walking yourself into peeing in
your underwear drawer?

*** Deeply Held Beliefs and "Narrative Threat"
One foothold of Amathia is the "deeply held belief." This sort of
belief, when questioned, provokes a response not dissimilar from the
fight-or-flight impulse of cold survivalism. For whatever reason, we
treat beliefs about how humans should behave on a social scale
(politics) similarly to how we treat notions of our own safety. It's
as though we view threats to society as a threat to ourselves. This is
probably an evolved mechanism, but we've long out-built many of our
adaptive and evolutionary mechanisms, and determining whether it is a
useful response or not is impossible.

We're not stupid. Any belief that we're going to give that much weight
is going to have reasons. Reasons that we've thought about and are
sure are unimpeachable. Beliefs aren't just one fact. Beliefs aren't
just one justification. Beliefs are filled with narrative goop that
fills in the cracks and removes doubt. But narratives are
theories. Beliefs are conjectures. The more facts that your narrative
relies on in order to be true, the less likely it is to capture truth
at all.

*** Hard Syncretions
All of this unfortunately leads to "third way" nonsense. Movements,
evangelism, and belief in something that exists "outside" of current
politics, but would impose a politics that is equally
unlikeable. Every position is extremist if you believe it hard
enough. The middle is a myth, a misunderstanding of politics in
general.

So much of what masquerades as moderate is just another one of these
new positions that fail to capture complexity and only serve as traps
for the intellectually lazy -- I've been lazy in a way that can only be
described as /ad nauseum/, so I really understand. If we're [[https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow][Thinking,
Fast and Slow]], we must always endeavor to think a little more slowly
about our foundational beliefs. Anything else is doing ourselves a
disservice.

True "moderation" has to be a rejection of hard and fast positions
that are immune to updating. There are no good firm beliefs because
beliefs cannot accurately capture reality in a meaningful way. I'm
sorry. I know this is hard for me.

*** Ontological Chicken Coop
We are led to believe that it is valorous to defend our beliefs. Even
the verb "defend" makes it seem as though it is a life or death
matter, that protecting the purity of our narrative is a top
priority. But valor has its limits as a virtue, and when overextended
it leads us to stubbornness.

Montaigne, speaking of physical battles, says that such stubborn
people are rightly punished for their actions. Otherwise, he says,
every chicken coop in every city would become a bastion for the city's
defense. It is up to the valorous to decide when the battle is lost
and surrender themselves up to judgment of those conquering.

The good news is that this "defense" metaphor is fucking
terrible. Absolutely god awful. There's no battle for your
ideas. Every conversation is an opportunity for constructive,
syncretic conscious agents to add some good stuff to their mental
models, and subtract some bad stuff. If every bit of your narrative is
a chicken coop, though, it's gonna be vomitously bad in there. We call
this code smell, in the biz.

Of course we see, culturally, shifts from one set of narratives to
another. The timeline over which it happens is simply much too
long. The internet's instanteity requires fast adaptation and
existential acceptance of the infinite flow of narrative-redefining
information.

*** Permissivity and Side Effects
If you've gotten this far, you're probably like "we get it, you read."
And that would only be half true, since most of what I read are blogs.
Blogs, like this one, are, by definition, bad. I haven't said anything
and here we are, as stupid as when we started.

If you've been reading this critically, who knows. Fuck off. Your
paranoia is welcome here, just don't let it stop me from brain washing
you.

That said, I'm pretty sure I plagiarized all of this. There's very
little to say in this world that hasn't been said better. That and I
have a pretty great memory for words, but not authors, so I'm probably
prone to the same sort of reckless plagiaristic recontextualization
that Fareed Zakaria is. Plus I used to really like his columns.

I'll leave you with this. Sometimes learning about new or painful
things doesn't indoctrinate you to the cause. Sometimes, if we allow
ourselves to think about how someone arrived at their conclusion we
can learn something besides what they've said. An off-label use of
their ideas. Sometimes these off-label uses should have been the
intended use all along. Maybe at some point culture will come around
to this notion, just as Benadryl is sold as both a sleep aid and an
allergy medication.

Wow that was a dumb way to end.
