#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Goal Plane
categories: attempts
---
#+END_EXPORT

* Goal Plane

** I. Context

Where do I fall on the spectrums that define mental illnesses? What
traits of my own are exaggerated and pronounced compared to the
population average? It's likely that more mental illnesses are
spectrum disorders than previously thought. If this is true, maybe
there are mental illnesses that can be understood by studying trait
behaviors that are present in a much larger portion of the
population. Depression, borderline personality, clinical anxiety,
paranoia -- it's easy to see where common personalities manage to
typify the traits of their less-common peers. At least one of my own
traits is exemplary: a hoarder's appetite for the seemingly pointless.

For a while now I've considered myself to be somewhere out along the
hoarder spectrum. I don't think I'm up for a clinical diagnosis (but
somehow something like *5%* of people are?  ?!), but I bump into the
emotional aspects of hoarding on a near daily basis. I understand the
deep regret that it's possible to feel when throwing something away
that /may just be/ useful in the future, no matter how unlikely that
possibility is. I understand the feeling that objects have intrinsic
value, and that it does them disservice to cast them aside. I
understand that seeing receipts or valueless mementos can trigger a
deep catharsis or vivid reliving of the moment associated with that
object. This even applies to the digital artifacts that accumulate on
my laptop -- shards of forgotten projects, screenshots, academic
papers whose subject matter I won't possibly be able to understand for
months. I understand that discarding trash(is it trash?) robs you of
the opportunity to experience those old wonders, now forgotten, like
they're new again.

This general understanding of my world as both *inherently* useful and
*inherently* emotional influences the way that I deal with general
reality (as such things are wont to do). I have a hard time leaving
places or homes. I have a hard time re-arranging furniture. I get very
sad when my belongings first begin to show signs of aging and I do
whatever I can to prevent that (curiously I haven't had any trouble
with my own aging process, yet, but I'm young). I struggle with making
changes to my physical appearance. I hate the weeks of discomfort in
my own skin when I get a haircut and I hate the way fashion changes
around me, leaving me with clothes I would rather not discard but an
appearance that is outdated and shabby. Even while editing this work
I've found the process of updating awkward phrases to be difficult:
I've already become attached to them.

The changing world makes me say a lengthy goodbye to the way that
things once were, goodbye to those configurations of the universe that
are never to be experienced again, and goodbye to my gradually earned
sense of comfort and routine.

Experiencing the world as thousands of tiny goodbyes can be
exhausting. I understand why hoarders just choose to avoid the
sensation as much as possible. Still, it's because of this exhaustion
that I feel that /emotion/ is just as present in the fabric of reality
as /space/ or /time/, and perceive that in many ways it is just as
inseparable from its fibers. It's on rare occasion that emotion seems
to precipitate out of reality and coalesce into something tangible,
something I can really sink my teeth into, touch, and feel. On these
occasions emotion's qualities can be more thoroughly studied, and its
hidden potential more thoroughly speculated upon.

** II. Emotion

Like most of our biological features, emotions are presumed to have
had some evolutionary purpose. Evolutionary biologists and
psychologists studying emotion have labored to discover what that
exact role might be. From my perspective, there's at least one
coherent theory that can be synthesized from this effort. Borrowing
heavily from the work of Richard Lazarus, this theory, a theory that
is adaptive, cognitive, motivational, and relational, posits that
emotions function as our interface to our /goals/, and as a primary
driver of adaptive behavior. This explanation seems almost too tidy,
but the theory is beautiful and explanatory, and from it we are able
to draw out indirect implications that are both interesting and
useful.

My rather loose sketch of the theory goes like this: our survival
requires us to complete a number of tasks for the sake of our personal
wellbeing, our societal wellbeing, and the production/wellbeing of our
offspring. The biological imperative springs eternal. Anything that's
needed for the completion of these tasks-- our order of operations,
our priorities, and our understanding of what is necessary (in other
words, our /strategies/) are all chunkable with this conception of a
/goal/. These goals form our goal hierarchy--the requirements for our
biological and social success. Any tools that we can evolve to more
effectively illuminate and reward the tasks that lead to those goals
(and thus increase their chance of completion), will be selected for
by evolutionary processes.

Emotions, then, are the tools that we evolved. They help us calibrate
both reality and our goals so that they are better aligned. They
provide us with invaluable information about ourselves in the world,
and how we exist in relation to our goals. In this mishmash theory of
emotion the information we receive from our emotions can be clear and
helpful. Happiness is understood as a signal that reasonable progress
has been made towards a goal, sadness is a failed or otherwise
irreparably lost goal, anger is in response to a temporary state of
failure (a failed attempt), frustration is a signal that something is
blocking progress towards a goal (perhaps unexpectedly), anxiety is
vigilance for outside threats to your goals, boredom is a sign that
your goals are stale, etc. The fact that some emotions are rewarding
and others are punishing does not at all diminish the information-like
quality of raw emotions.

Some of these emotions are strong indicators that there is work to be
done on the outside world: anger and frustration indicate that we
should direct our (sometimes negative) energy at a target or problem
for the sake of a goal. On the other hand, some emotions are strong
indicators that we should work on our inner world: boredom and sadness
(ennui perhaps a subtle mix of the two) let us know when it is time to
change course and identify new priorities, goals, and tasking.

We can see these signals /in situ/ with the five stages of grief. We
will initially deny the information from our emotions, hoping that it
may just be noise in the signal, a misreading. After you are convinced
of the information, anger and bargaining are two halves of the same
coin -- alerting you that reality could better fit your goals, that
you could overcome the source of grief, that you can strike out
against whatever it is that's in your way. Depression is sadness, a
signal to move on when the object of your goal is irreparably
lost. Acceptance, finally, is the indication that, having exhausted
your options, you can resume with your other goals. I don't mean to
dismiss loss as "just" the loss of goals. In fact, if this particular
blend of theories of emotion is true, I find it quite beautiful that
one of our most instinctual, basic goals as human beings is to find
and love one another, and to care for and protect each other. It's
intensely poetic that in order to adequately signal to our brains that
all is lost and that we can move on, our body has to cripple us with
sadness for days, weeks, months, or years.

** III. Goal

Since I feel like reality has *inherent* emotion and *inherent*
usefulness, and since I feel like /emotion/ and /use/ are both proxies
for something else, maybe what is present in the fabric of reality is,
in fact, /goal/.

/Goal/ manifests as a dimension outside of the three that we're used
to thinking about, or like the ethereal plane from the pathfinder
canon. It's easy to forget that there even is a /goal plane/ (the
extra layer of reality, or "surreality" to borrow a term from Robert
C. Solomon), perhaps until we experience loss. Sadness and frustration
make the /goal/ more obvious. Again thinking in Solomon's terms (from
"The Passions"), it's these moments of transition between goals
(values and meanings) where we are most often confronted with some
absurd reality, that we did not recognize until this very second to be
the /goal plane/. Without sadness and the other hints that we've lost
something, there'd be little reason to believe that there was anything
there at all. Like wandering a darkened room, it's smooth traveling in
any direction while there's nothing in the way, but without clues
about what lies ahead it's easy to become disoriented, hands flailing
for purchase. The bump, when it happens, is both unpleasant and
orienting, helpful and hurtful.

Within the dark room of this surreality, this /goal plane/, it becomes
apparent that our emotions function like /sensors/, like an actual
perceptual faculty for investigating and navigating the darkness. This
inverts our usual thinking. We think about emotion as something that
happen to us in response to thought (a purely cognitive model of
emotion) or in response to physical perception (a purely somatic
model), when in reality even the combination of the two is only half
of the picture. In order to make sense of the world around us our
minds (both conscious and unconscious) process information about goal,
courtesy of our emotions, /alongside/ information from our physical
senses. The synthesis and transcendence of these multiple sources of
information ultimately guides our action.

Consider, by way of example, the venerable list of "Pros and Cons". If
you've ever written one you may recognize that the actual numerical
number of pros and cons--the "sizes" of which are subjective, and the
consequences of which are often incomparable--have little to do with
the decision you make. Making the list is a way of systematically
observing emotional information about the different consequences of a
choice (a "choice" here having very little representation in the
physical dimensions, but having a significant presence within goal
itself). Our observation of goal resembles our observation of a
physical reality. The topology of the goals--as we sense it--is
reflected in the emotions it activates, like how frequencies of light
activate rods and cones as they strike the retina. Modern cognitive
behavioral therapy, classical Stoicism, and many lines of Buddhism all
understand that emotion is something that can be observed, understood,
and acted upon--just like our physical reality (although they may not
say so in as many words).

Our goal plane is incredibly personal, like a fingerprint of our
values. Goal uniquely affects our individual realities like gravity
affects our shared one. Goals exert their forces on us, and with the
help of our emotions we follow: like a rock resting in a local minimum
as it rolls down a hill. Or, at an astronomical scale: like an
asteroid captured as it wanders lazily into a planet's gravitational
pull. Anger and obsession encourage you to spiral in, borne by your
own momentum. You can work to change course, but it requires conscious
effort. Through overcoming sadness or enduring boredom, you can work
to change goals. Even then the attachments of your previous goals
(relationships?  routines?  precious moments?) prevent you from
totally settling at the bottom of a new goal-well, an inflection point
in your surreality, until the force of time overcomes the old force of
goal.

The way that I've mourned as I've departed the old homes of my
childhood, refused to erase whiteboards containing sentimental notes,
or kept tickets from events that happened months ago only serves to
illustrate how intensely the ripples of yesterday's goals still
influence me today. Peoples' blind rush to throw away the ephemera of
old relationships is another potent example. What is it about an
object or place that warrants its destruction or preservation? What
about its conception in your mind conveys any value, both positive and
negative?  These questions are perhaps especially notable when the
object itself is innocent of any crime against you, and absent of any
particular favor.

This kind of attachment seems like a fundamental human
experience. While not exactly obvious, these attachments are our
personal directives, our biological incentives, and more. These
/individual/ goals (and realities), while sticky and fraught, are
still relatively easy. A significant portion of interest and conflict
occurs where realities overlap: when we find ourselves occupying the
same time and space as others, but with disparate sentiments and
intentions attached to our surroundings, our physical bodies, the
physical bodies of others, and our mental orientation.

In these circumstances we can attempt to communicate our differences
and provide a dialectical, communal, revision of goal. Language is a
primary tool for this sharing and realigning process. There are also
coarser grained emotional tools like violence or physical isolation,
and more impressionistic tactics like weeping openly, scowling,
laughing, etc. These are often seen as a last resort for our
communication. The ability to coordinate without open displays of
emotion or coerce without shows of strength is part of what makes us
uniquely human.

If we have our own goals, and we occasionally try to use language and
other tools to influence the goals of others, it seems to follow that
even though every little critter has its own little goal-plane (goal
dimension?) that it comfortably wanders about, sensing lazily -- every
little critter's plane is also /hopelessly/ intertwined with the
goal-planes of everyone else. Our families, our tribes, and our cities
all behave the way that they do because of our goals, now entangled
with the goals of our neighbors, loved ones, friends, and
acquaintances. This is the social fabric, our cultural existence, the
reality that all human constructs must be deconstructed into. For
ease, and for clarity going forward, I will now call this entangled
super-set of all goal-planes /Zeitgeist/.

** IV. Spirit of the Age

/Zeitgeist/ can be understood as a literal, genuine, bonafide,
physical property of reality. It's the actual code of the
simulation. It's god's plan for us all. Whatever. It doesn't matter
what it is. It's there as an emergent property, or as an inbuilt
characteristic. When thinking things cohabitate reality, their goals
exist in superposition, an indeterminate fuzz of values and meanings,
a static from the heavens. Our personal goal-planes, our own
directives and the emotions that they evoke, are just the part of
zeitgeist that we are personally tuned to receive.

With "rods and cones" and other features of eyes, animals (and some
humans) have evolved to see various portions of the electro-magnetic
spectrum. In the case of zeitgeist, /every individual person/ is
specifically adapted to perceive a different cross-section of it, and
this cross section just barely overlaps with the cross-sections of
other people. No one has the same emotional response to zeitgeist as
you because no one can perceive the same part of the emotional
landscape. While for /most/ features of zeitgeist we humans can agree
that there's /something/ there, we usually can't agree on its salient
features. Occasionally there are forms within zeitgeist that totally
elude us. These differences in emotional interface are where meaning
lives. Meanings are derivative of the goals present in reality. Value
is derivative of these meanings. Asking "which goals are we sensing?"
and "how intensely?", and "with what emotion?" helps us locate our
individual values and our individual meanings.

# ^^^ this section can be expanded into its own attempt

Of course, where there is meaning there is
synchronicity. Synchronicity is a natural formation of goal atop an
otherwise uninteresting physical reality. The physical happenstance of
the world, such as bumping into someone at just the right moment, or
seeing a 1984 AMC Eagle after you were /just/ talking about how you
/love/ 1984 AMC Eagle 4x4s -- events that would merely be pleasant
without a prior instantiation of goal, are perceived as meaningful by
our sensory organs, because /they *are* meaningful and we can detect
it/. This feedback between our physical perceptual organs and our
perceptual organs that operate in the much spookier plane of goals and
meanings is what generates our luck, chance, and happenstance. Is a
particular coin flip or dice roll "lucky" without considering the
goals of the players?

This line of interrogation and its mapping to the physical domain is
particularly fruitful. Do you see the same green as other people?
Probably not. Do other people perceive the same aspect of zeitgeist as
you?  Probably not. Do things mean the same thing to you as they do to
other people? Again, no. Given this, will you perceive the same events as
lucky or coincidental? Unlikely.

There are many things like this that seem to exist entirely within
zeitgeist. The psychic groupings of [[https://en.wikipedia.org/wiki/Egregore][egregores]] (distributed,
goal-converging thoughtforms) and [[https://hermetic.com/bey/taz3][temporary autonomous zones]] (places
where unmediated existence emerges temporarily in response to shared
vision), for example, must exist where the physical world is a mere
afterthought-- like with synchronicity and luck.

Next I can't help but think of Art, which seems to be a manifestation
of pure zeitgeist. It is meaningless without an artist's (or scene's)
goals, and the goals' juxtaposition with time and space. An artist's
hands massage zeitgeist into an appealing form. The physical medium is
incidental, or functions as a focus for the form. Our good taste, our
ability to possess discernment about things with an artistic element,
is about effectively mapping the relationship between ourself and any
object of culture (or artwork) within zeitgeist. Locating something
with GPS-like precision is the mark of a tasteful
individual. Beyond taste, celebrity is the result of twofold: one's actual
position in (now 5) dimensional space, and the preponderance of goal
present in oneself. If you're not in the right place, time, and locus
within zeitgeist, you're not a celebrity.

# ^^^ this section can be expanded into its own attempt

All of these things are the purview of the "humanities." Within them,
sociology is most explicitly the study of zeitgeist, since the
emotions and goals that form the organizing principles of groups of
humans only exist within this entangled goal-dimension. Surveys, then,
are a /finite/ sociological tool designed to measure the /continuous/
surface of zeitgeist. These surveys and methods may be accurate to
some extent, but they obscure the fractal detail unfolding beneath
them, and once obscured it's easy enough to forget that those details
exist in the first place. We mistake a tracing of the surface of the
thing for the thing itself. Related fields, like ethnomethodology and
political philosophy purport to explore zeitgeist in other ways, with
other tools, with other downsides, and by making different
assumptions.

If emotion allows us to perceive our own goals, I will speculate that
reflective empathy, theory of mind, and their more effortful cognitive
cousins are the perceptual organs that allow us to perceive the
zeitgeist around us. They even allow us to conceive of what zeitgeist
looks like from other orientations and angles, a key component of taste and
celebrity. Like how prior sensory knowledge of the shape of an object
allows us to simulate how that object must /look/ from another
perspective, knowledge of what an object /means/ to someone else helps
us simulate the view of another facet of zeitgeist. These simulations
are crude, like drawing from memory, but at least they're available.

** V. The Nature of the Perceptual Organ

# This can be expanded, perhaps with personal anecdote

Touch, sight, hearing, and chronoception, as human sensory
capabilities, are subject to human limitations. Our perception of
zeitgeist, as a human sensory capability, is no exception. We
understand our own motivations and of the motivations of others
through an interface that is mediated by time, distance, and innate
perceptual ability.

Emotional acuity varies from person to person. Sometimes our
perception is limited locally by mood swings or through the spectrum
disorders mentioned earlier. Our over or underestimation of
something's importance is best likened to a sensor malfunction or
mis-calibration, but, like with eyes that are blurry or with ears that
are dull, there are ways to augment our emotional acuity. With our
physical world we can put on eye-glasses or use tools to do our
sensing. When it comes to the emotional realm of zeitgeist, these
augmentations are cognitive improvements (thought technologies) for
improving our emotional interpretation and better mental
representations of the goals and emotions of others. Emotional
intelligence can compensate for a deficit in the sensors. We can build
perceptual lenses that help correct for our inadequacies.

In recent history another corrective alternative has emerged: the
administration of pharmaceuticals. We have just barely begun to
understand this process. We didn't know until recently that common
drugs like acetaminophen influence the way we perceive
emotion. Acetaminophen dampens our own perception of pain, and
(presumably through related mechanisms) dampens our perception of
others' pain as well. It has even been suggested that acetaminophen
can pull us out of an existential crisis-- as though existential pain
is a pain to be "killed," as well. Stimulants, by comparison, change
our emotional acuity by increasing our positive perception of goal in
common tasks and general executive function (and also making that
Youtube hole just /that/ much more enjoyable). Anti-depressants
decrease the presence of sadness in our palette of responses, like
rose-tinged glasses for our soul.

Spatially reckoning, zeitgeist is very large. It's as long as the
universe is wide. Wherever there's life, goal follows. This means that
zeitgeist contains exactly as many goal-planes as there are thinking
creatures in this whole universe. Each goal-plane only thickens
zeitgeist. It's dense, complex, enormous, and we can only perceive so
much of it.

Just like being physically isolated from the existence of other human
beings, or existing in another time from other human beings, we can be
isolated by existing in another aspect of zeitgeist. There have
already been 100 billion human beings, and you can only know what, a
few thousand? If your goal-plane is not closely entangled with another
person's, you will not have the occasion to interact with them. This
is especially apparent in the internet age, where physical isolations
are less important to our overall connectedness, and the opportunities
created by shared or similar goal flare in consequence. Of course the
"occasion to interact" is not the end of the influence of
zeitgeist. Goal can steer those far away, who you have no
knowledge of, into action that affects you and your own goal. This is
perhaps the case with the CEOs of coal companies, or the actors in the
global political theater, or even average consumers steering the
pricing and materials of consumer goods.

While the internet has the potential to entangle goals across great
distances, "filter bubbles" are a disentangling (isolating action) of
otherwise complex interactions in zeitgeist. They are powerful
positive feedback loops within goal itself. They are loci where the
topology of zeitgeist reaches upwards towards infinity. Filter bubbles
are machine augmented, but they have existed since the dawn of
civilization. We pick our friends and acquaintances in accordance with
our goals, and in the process we disentangle ourselves from the goals
of people that we perceive as different from ourselves. The good news
is that zeitgeist, while perhaps less malleable than space, is
definitely more malleable than time-- and there are definite discrete
actions that we can take to influence our own goal-plane and the
greater zeitgeist. The state of the world at any point in the future
is essentially the current reality + physics + goals + time, since any
change that the universe experiences that is indescribable through
simple physics can be described by the interactions of the goals of
the intelligent beings that inhabit it.

** VI. The Space

Given this conception of zeitgeist as

1. Present in reality
2. Exerting influence on us and therefore
3. "Sense-able", like space and time
4. Malleable, like space and (to a lesser extent) time and,
5. Vast, like space and time

we can start to conceptualize its shape, its isomorphisms in other
thought, and its consequences in the real world.

Zeitgeist provides a term of art for the occasions on which we must
roughly quantify the effects of our actions. It vivifies the
“supra-individual” realm, the social fabric, cultural fabric,
emotional landscape, and the interactions spinning out therefrom. It
does so without straining the brain too hard. A psychic space that
behaves like a physical one allows analogies to flow more
readily. I've already mentioned "wells," as though ruminating on
gravity and orbital mechanics.

The landscape is defined by the dimensions of our experience. In time
there are moments, in space there are points, in zeitgeist there are
loci. A humane coordinate system, and the rhizome runneth through
it. A tree is planted at this locus or that. The emptiness of outer
space may be an equally empty outer zeitgeist.

We pilot our little space-ship brain between goal-wells, taking care
not to get drawn in. We apply our energy to vector towards particular
goals or to vector away. Achieving either will be hard (as we perceive
frustration or sadness), and either way the results of our efforts
will land us in very different regions of space. Most of this space
has very little goal associated with it, but occasionally the
preponderance of goal in a person, place, event, or thing behaves more
like a black-hole than anything else. The cosmos seems to revolve
around these points, thick and dense. An "erratic" orbit becomes a
sign of outside forces acting on the situation. Maybe that's our
intentional vectoring at play, maybe it's an encounter with an
entirely new cosmos of goal.

Do you ever think about a thing that just seems "big"? Have you ever
inspected the thing's "bigness" only to find that its actual reach is
limited and human? Has that ever happened but the thing still felt
"big"?  We can chip away at zeitgeist and attempt to change its pull,
but we are small and sometimes the pull is too strong.

Just like the physical world, we change zeitgeist as it changes
us. Also just like the physical world, we are capable of acting on
multiple different scales, magnitudes, and levels of
analysis. Zeitgeist can be sculpted on the micro-level. Artistic
effort, frank conversations with friends, precisely situated remarks,
opinions shared flippantly, and condescending dismissals on Twitter
can all stack rocks or tumble them, carve detail or cut it
away. Large-scale works of art and activism are quotidian earthworks,
the back-hoes, bulldozers, and dump-trucks of working with
zeitgeist. Someday we might have planet-scale tools to move the
heavens and the celestial loci beneath them, but like physical tools
of the same magnitude they are still beyond our technological
imagination.

Goal can also be accumulated or re-purposed. The rare gem can be
extracted and cut fashionably, elevating it in value and
importance. This is the purview of historians, journalists, and
taste-makers, who find substance in zeitgeist and inflate its
self-contained goal with artificial attention. Here we find ourselves
in a strange loop: in order to change zeitgeist intentionally, we must
expand zeitgeist so that it contains itself and any intention you may
have towards it from this moment onward.

Politics exists in this strange-loop as a very un-self-aware attempt
at organizing around and changing zeitgeist. Doing politics
intentionally is impossible without assimilating the continuous
surface that contains opinion, policy, strategy, and emotion
simultaneously. On the other hand, political extremism is a slippery
slope into a new part of zeitgeist. The forces are isolating and
strong, as the slope is steep and sparsely populated. Those that fall
into this particular hole are difficult to save, and find themselves
impotently raging for an ideology that isn't worth the time or energy.

** VII. The Locus

Physical perceptions are only part of the human perceptual
gamut. Perceiving zeitgeist is in many ways more beneficial than
perceiving the physical world. Systems that perceive utility (value)
out compete those that perceive reality. The blind, deaf, and numb are
all impossibly more capable at dealing with a general reality than the
best trained neural-net classifiers. Your goal receptors are your most
valuable sense. Professionals almost always "trust their gut" above
all else -- which seems an almost hideously obvious allusion to the
use of your emotions as perception.

The adaptive theory of emotion, the current version of which has been
around for almost 40 years, and which can trace its thinking back to
Darwin, has set this line of inquiry in motion for a variety of
crackpots (and some reputable individuals) like me. I hope that the
status of such speculations can move from "wild flight of fancy" to
"viable thought technology."  Thinking of value and meaning in this
way, and having a new set of terms for discussing policy, people, and
socio-cultural institutions could be helpful. Discussions of personal
value, and our conversations about the breakdowns and sticking points
in relationships with family and friends take on a new character as we
enable the fundamental physical metaphors and make them explicit.

It's disappointing that there is no way to measure zeitgeist
directly. There is no way to verify a hypotheses about it, unless your
hypothesis is about population level statistical averages. And then,
because of the nature of averages, and since the tools at your
disposal are generally survey instruments from the fraught fields of
sociology and psychology, you are unlikely to capture the continuous
reality that underlies the results. Identifying a few points and
creating a map from lines drawn through them does nothing to explore
the territory.

Despite this it feels like a new realm to explore, full of deep magick
and occult arts. It feels like a whole new planet, whose inhabitants
possess technologies that are essentially pre-scientific. More than
that, it feels like an appropriate partner to our internal narrator,
that fills some of the gaps around what most people think they know
about the brain. It also feels as though artificial intelligence
researchers will need to develop some goal sensors.

In the meantime, it's an interesting inversion-- a mental slight of
hand. The value (I hope) is in the new analogies, enabled.


** Some Very Loose References

*** [[http://www.mdpi.com/2076-328X/3/3/459/htm][On the Function of Boredom]]

Best summary of the adaptive theory of emotion that I've seen, in
service of introducing boredom as a distinct emotion in the theory.

*** [[http://www.cogsci.uci.edu/~ddhoff/interface.pdf][Interface theory of human perception]]

Simulation research that "proves" that better knowledge of physical
reality will be out-evolved by better knowledge of value.

*** [[https://www.psychologicalscience.org/news/releases/experiencing-existential-dread-tylenol-may-do-the-trick.html][Acetaminophen for existential crisis]] / [[https://academic.oup.com/scan/article/11/9/1345/2224135/From-painkiller-to-empathy-killer-acetaminophen?searchresult=1][Empathy reduction]]

Notes on pharmaceuticals (Acetaminophen in this case) changing our
emotional response.

*** [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4125199/][Extreme Traits as Personality Disorders]]

Overview of traits as disorders.


/A very special thanks to everyone who provided feedback on earlier drafts, especially Mitchell Finzel, Benjamin Cole, and Jane Rennick, who puked the first time she heard this idea (unrelated). Greg Maher provided much needed notes to contribute to a second revision of this essay./
