#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Why to blog
categories: attempts
---
#+END_EXPORT
** Why to blog
*** Sexual Release
    Blogging feels great! It's normal and healthy. Average men blog
    anywhere between once a week and twice a day. Whatever feels
    right! As long as you're still making time for your family and
    friends, and not neglecting your responsibilities, it's fine to
    keep blogging.

    If you're new to blogging like I am, talking about blogging with
    your family and friends can be scary. Start small. Maybe make some
    jokes. Think about your own comfort first, and go slow. Light some
    candles! This is you time.

    It's all about the release, babey!

*** That sweet bloggo cash
    The internet is a platform for delivering ads. If you want people
    to see ads, you should consider bloggong. Lots of people read
    blogs, all over the world. I wanted a slice of that sweet bloggo
    cash, so I started this blog. Now, I might make some money.

    Ads should be tasteful and relevant to your audience. Personally I
    don't like a lot of bloinking lights or scantily clad people (sex
    sells but not to me).

*** Internet fame
    Almost all famous people blog. This much is fact. Many famous
    people even started blogging before they got famous. Lots of
    people keep travel blogs or post photos of their food these
    days. Sometimes obscenely large numbers of people look at your
    pictures of food and then you are, what they call, internet
    famous. Okay so humor isn't my strong suite.

    You may have a few hundred readers or you may have a few readers
    but either way, your blog is a tangible way to get yourself out
    there for your friends to read. If you're inclined to blog you're
    probably not posting a lot on facbook or twitter, so this may be
    the only way.

*** Makes a good resume bulletpoint
    If your blog is in a public place recruiters will probably see all
    your posts, so you should feel free to include it in your
    resume. It signals initiative and also, even if it's bad it's not
    embarrassing. Words on a web page are just words. An experimental
    playground for ideas. There are no bad questions, only bad
    answers.

*** Impress your friends
    Blogging is a status symbol. Blog, smoke, sex, repeat.

*** Be smart
    One good trend I've been seeing lately is that some smart people
    keep blogs. If smart people make blogs then more regular people
    can read the contents of those blogs. I personally read many hours
    of blog daily, and can say that my thinking and reading skills
    have vastly improved. Also I definitely don't believe in the dark
    enlightenment now. I told my girlfriend I wanted to blog about
    ontologies because the word ontology was something I learned in my
    philosophy class in college.

    Don't believe everything you read online, but I'd say that blogs
    are of above average reliability. I plan to only publish reliable
    things, so you can trust me.

    All I know is, even if you can't be smart, you can at least relate
    to that #1 [[Sexual Release][tip]].
