#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Ambition
---
#+END_EXPORT

** Ambition
Ambition is a sticky subject. I think I used to have it. Now I'm not
sure I do. I don't know if I have the stomach for ambition. I'd rather
keep working in records, thanks.

Ambition is a will to succeed? An "an ardent desire for rank, fame, or
power" from [[https://www.merriam-webster.com/dictionary/ambition][M.W.]] /Ambitious/ is how we describe politicians, actors,
and CEOs. Ambition is desirable in a partner. Ambition garners status
and praise. Ambition often disappoints.

"Rank, fame, or power." The traditional signifiers of success. The
tricks we played on men to encourage them to take great risks and
incur great rewards, with the great@@html:<i>@@er@@html:</i>@@ good in mind.

*** Success
Success is incumbent upon either extreme singlemindedness and luck, or
extreme luck and singlemindedness. In the modern world you must
specialize to break out. The generalist is useful, but
unrecognized. You don't find internet fame writing a blog post twice a
year and occasionally re-plumbing your home. You don't get recorded in
the annals of history for your mediocre punditry and passable game of
golf. You don't make buckets of money working part-time on your
dream. Unless they have the great luck to be born into it, wealth and
fame will not find the scattered and undisciplined.

Ambition is fuel for singlemindedness. It overrides the desire for a
temperate life and forces the mind into the narrow channels that lead
towards success. It coerces thought, justifies action, and encourages
us to 'other' those that aren't on the same path. What do people have,
if not things to contribute? Get on the train or get out of the way.

Ambition--success--needs you to /know/ that you're on the right path,
that this is what you are /meant/ to do, as if given instructions from
above. It requires a certain arrogance to believe that.

*** Pro-social(?) amathia
It /requires/ a conceited ignorance of the plurality of choices spread out
before you. Your choice of occupation, of endeavor, of way of life--
this is the one. Or maybe your endeavor is to find the one, and you're
sure that you can find it.

The results can be tragic. Ambition kills. Every great leader, and
especially every great murderer, had ambition. Amathia /is/ what
powers fascism; ambition the most human application of pure fervor.

The results can also be incredible. Ambition just may be the most
beneficial application of ignorance that has ever existed.

*** Melancholy
Melancholy is the natural enemy of ambition. Sadness may [[https://en.wikipedia.org/wiki/Melancholia#Art_movement][occasionally]]
inspire great art, but sadness without ambition cannot compete in a
world filled with discontent and drive. Sadness is the end of a
struggle, the battle lost, the talent forgotten, the friendship
over. To exist in total sadness is to exist without goals. Complete
anhedonia is to exist without motivation.

Part of the draw of a city like New York or LA is that everyone is out
there striving for something. People go there to prove something, to
"make something of themselves," and find fame and fortune. This is all
well and good, but for reference, actors make up .02% of the
population and CEOs of publicly traded companies just .0006%. Still,
if you don't think about it too much it's easier to ride the wave and
strive for something of your own when there's actually a wave to ride.

Seemingly opposed are communities that excel at providing
contentment. These places have strong communities, relaxed identity,
good social services, and plenty of public hedonism.

These cities, like Minneapolis, Portland, or Boulder, offer something
to the melancholic that the big cities can't: the consideration that
just getting along and finding happiness is enough. Owning a small
business, contributing something to a local festival, hell--even
inviting some friends out to that local festival and enjoying the
day--this is enough.

*** Eudaimonia
Bliss is on the other side of melancholy, and quiet goallessness the
sensation of [[post:2017-03-01-travel-blog.org][salience]].

How do we strive without ambition? How do we find meaning in sadness?
What is achievement without rank, fame, or power? Is contentment
enough?
