#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Untying Knots
categories: attempts
---
#+END_EXPORT


* Untying Knots: Suspicion in the 21st Century

#+BEGIN_QUOTE
Problems cannot be \\
Resolved at once. \\
Slowly untie knots \\
Divide to conquer.

-- Deng Ming-Dao
#+END_QUOTE

When parsing the sometimes erudite musings of the meta-rational
internet, you must give the gamut of ideas cool consideration,
weighing post-modern, modern, and medieval alike; refusing to give in
to the demands of systems that are too quick to declare truth, too
fixed in their understanding, and, from these initial shortcomings,
too unwilling to engage in solutions. From the flexibility in its own
ideology stems a general unease with the state of things-- the
unwillingness to talk, the obstructionism, the /ad hominem/ nature of
nearly all argument at the national level, the constant poisoning of
the well, and the tendency of the internet to amplify these features
as commentators sit miles away, safe behind their computer screens,
with virtually no chance of consequences for behavior that would be
absolutely abhorrent if executed in the IRL. Couple this with an
intellectual milieu that is both combative and elitist, and it's clear
that the global conversation leaves much to be desired. What's the
problem?

In recent months, it appears to me that the internet's brightest
thinkers have been circling the drain, attempting to converge on a
common enemy. It also seems to me that they've come to an informal
conclusion: the enemy in academia is /critique's/ election to its
current status as knowledge's best excavator -- privileged among tools
to unearth true meaning, shatter the facade of previous knowledges,
and expose artifice.

From Heather MacDonald in the Spring 2017 issue of [[https://www.city-journal.org/html/true-purpose-university-15134.html][City Journal,]] to
Fuck Thought's [[https://www.artforum.com/slant/id=65193][Syllabus for the End of Times]], to the endless critique
of critique I see in the wild, it's become clear that if we go for a
dive in the tepid water that is drowning modern academia, we'll find
wads of lackluster critical practices stuffed--enthusiastically--into
the drain. It seems inescapable. Rita Felski hit the nail on the head
in her 2012 essay "Critique and the Hermeneutics of Suspicion":

#+BEGIN_QUOTE
Critique is contagious and charismatic, drawing everything
around it into its field of force, marking the boundaries of what
counts as serious thought. For many scholars in the humanities, it is
not just one good thing but the only conceivable thing. Who would want
to be associated with the bad smell of the uncritical?

-- [[http://www.journal.media-culture.org.au/index.php/mcjournal/article/view/431][Rita Felski]]
#+END_QUOTE

To be uncritical is to be unthinking, and the unthinking is the stooge
of social consensus. Critique is /how we get better/, so we better
keep doing it.

It's more than that. As Hanzi Freinacht has [[http://metamoderna.org/4-things-that-make-the-alt-right-postmodern?lang=en][noted]], the reflex to
critique, through critique's own negative affect, becomes a reflex to
dismiss: "a proposal dismissed is a job well done," and this reflex to
dismiss is pan-political and self-escalating. A strong critical
reading looks and feels like paranoia: it looks to root out what has
not been said, who was implicitly or tacitly targeted or erased by the
work, and who any co-conspirators might be. Who benefits? Who profits?
Why are they doing this? Maybe the reason is the establishment of a
New World Order, or maybe it's the buttressing of the Old. Maybe the
dichotomy between the two must be examined critically for better
understanding. Whatever way, critical contextual analysis is the name
of the game.

Things dismissed tend to dismiss in turn. Urbanites dismiss country
folk as bumpkins and those same bumpkins will not hesitate to dismiss
urbanites as city-slickers. In rural senate races representatives are
raked over the coals for spending too much time in the city. Anyone so
comfortable with the concrete and at ease with the constant noise of
the city must have an agenda that dismisses country-folk and belittles
their needs, common rhetoric would indicate.

Eventually dismissal out of hand becomes a relegation to taboo, and
soon those ideas gain a certain dark psychic power, a counter-cultural
veneer.

Who can say whether short-circuiting an idea with taboo or allowing it
to vanish (through audience) into banality is more effective? There
are probably other options. Who knows? With few sociological tools
equipped to handle such inquisitions, the temptation always remains to
critique and dismiss, taboo and censor.

So here I will attempt to array the constituent parts of critique with
some accuracy, make merry in the mechanisms themselves, and slide like
oil between the gears, happy for the tooth-edged gap in which I
play. The joy of the meta-critical.

** Postmodernism and the privileging of the paranoid process
At some point postmodernity gave up. Critiquing the fundamental logic
that underpinned the world's meta-narratives gave way to critiques of
the logic of the /dominant/ meta-narratives, with diminishing
recognition that we have little reason to assume that /any/ narrative
is more correct than the next. The postmodern got a little less crazy
in its eternal september. A certain moral contamination began to work
against the deconstructive impulse, rendering deconstruction itself
nearly unable to introspect.

Under these new rules, instead of attempting to understand /what/ has
been said, drawing from spatio-temporal clues to create dialogue
between texts and situate words in the historical conversation, we
must instead use those same clues to determine /why/ something is
being said, with a suspicious eye turned towards the biases and
/regimes of truth/ that fascistically ensnare the modern thinker. In
this new regime @@html:<i>@@con@@html:</i>@@text finds itself
transformed into @@html:<i>@@sub@@html:</i>@@text, a new, fertile
ground for paranoia.

These contemporary readings, in their search to justify their
paranoia, read implicit bias unless explicitly noted, and throw into
question the validity of modern ways of knowing, [[http://onlinelibrary.wiley.com/doi/10.1111/j.1741-6787.2006.00058.x/full][occasionally]]
including the thoroughly vanilla epistemologies of modern
post-positivism (the /tl;dr/ of post-positivism being that scientific
truths are statistical and conjectural in nature, and that human
biases pollute the search for truth). This even exactly the point. The
more vanilla and everyday our knowledge seems, the more likely it is
to be polluted, these methods proclaim.

With no hold on the truth, and the pure, fertile land of paranoia
stretching out to the edges of our vision, it now, in a deconstruct-y
ouvre-of-the-modern-times critique-y sort of way, seems our
hegemonically imposed duty to find the fault in whatever we are doing
and throw the grain of truth away with the bath water. Or something
like that. Read this:

#+BEGIN_QUOTE
The man of suspicion double-bluffing the man of guile: in the hands of
thinkers after Freud, paranoia has by now candidly become less a
diagnosis than a prescription. In a world where no one need be
delusional to find evidence of systemic oppression, to theorize out of
anything but a paranoid critical stance has come to seem naive, pious,
or complaisant.

--Eve Kosofsky Sedgwick, /Paranoid Reading, Reparative Reading/
#+END_QUOTE

Written in 2003, Sedgwick's work seems prescient in a world that now
seems absolutely overrun by the critical. Not even the critical, the
/pop/-critical. Even the un-paranoid that lay mercifully outside of
the academy now seem naive and ignorant. Paranoia escaped academia and
infected the masses. Maybe.

Unfortunately, this isn't where paranoia's reach ends. Paranoia
continues to be self-propagating, a property of the affect that is
also explored in detail by Sedgwick.

#+BEGIN_QUOTE
[P]aranoia tends to be contagious; more specifically, paranoia is drawn
toward and tends to construct symmetrical relations, in particular,
symmetrical epistemologies.

--Eve Kosofsky Sedgwick, /Paranoid Reading, Reparative Reading/
#+END_QUOTE

The brutal truth that paranoia is only truly understood by being
paranoid, a process that, once engaged, limits recourse for its object
such that there's very little option but for it to conduct itself in a
paranoid manner as well.

# *** Ricoeur

# *** Critical Theory

# *** Re-cap, sympathies for Marx

I don't even disagree(do even agree?) with the prescription of greater
imagination and new ways of thinking that much of post-modernism
revolves around. And that's the point. It's the suspicious modes and
mimetic mechanisms of paranoia that are not well suited for a world
where every idiot with a computer can type words and transmit
half-formed ideas at the speed of light. We need ways of thinking that
can deal effectively with the information firehose, and unfortunately
postmodern critical methods don't seem up to the task.



** Fascism and politics empowered by paranoia
We can hardly get through a sentence of an opposing partisan's view
without identifying them as a bad actor. With any inspection at all it
seems as though our governors are engaged in myriad conspiracies to
maintain the global oligarchy and undermine the working people. How
you imagine that's being done, and which oligarchs you think are being
aided, is probably what defines your politic.

# Objects of paranoia, outgroup, signifiers

# *** Fascism as a stand in for political "other"
# Attempts on left and right to create new paranoid outgroup of fascist

# **** Right calls no-platformers and gun-control activists "fascist"
# **** Left calls any racist or sexist fascist, in extreme cases just those who disagree

With that, do our political (narrative?) preferences manifest
themselves as tribes of paranoia(the other way aroud?)? Is it the
stories we tell ourselves about causality and the direction present
therein that define our fears, worries, and preferences? Are the
mimetic forces of paranoia what drive our [[http://slatestarcodex.com/2014/09/30/i-can-tolerate-anything-except-the-outgroup/][insane]] in-group preferences
and out-group banishment?

# May want to note stats or papers about political hiring preferences

Given how strong the forces are that deem to divide us, it seems
unlikely that the explanation is mere serendipity. It even,
increasingly, seems unlikely that divisions are drawn up along the
borders of race, religion, or language. From my vantage point it looks
most likely that tribal lines are drawn along the lines of shared
suspicion-- now empowered by narrative and promulgated by academically
mandated critique.

** Journalism, Punditry, Blog Post, Narrative

# These next few paragraphs are disjointed
There is an intelligensial subculture, born from new paths to fame and
notoriety, justified through calls to the truth, financed by
persuasion made monetary, and tasked with creating narrative from mere
fact. Situated in this, pundits are a particular type of commentator whose sole
job it is to find speculation, take it for a swim with what they "know",
and spit it back out. Journalists and bloggers may not accept the
pundit identity, but will engage in punditry nonetheless.

Professionals like these have become adept at simultaneously thinking
paranoiacally and fitting facts into ideology -- explicitly at a 12th
grade reading level. Their status as both accessible and "correct" has
sequestered them in a class of their own. The paranoid
class. Purveyors of narrative. Unwitting(or witting) shapers of
reality.

This class writes (or speaks) a lot. It's their job. The more opinions
that they can get out of their head and into the air the better. I bet
you could correlate global warming and pundit word counts.

To willing subjects consuming punditry or journalism (perhaps what
they're reading signaled all of the right values before they've even
begun), the sparse nature of text allows the reader to project
themselves into the gaps, taking only emotional cues, leaving only
agreement. To unwilling readers, the gaps in the text seem to be
filled /with the writer/, allowing paranoid interpretive reflexes to
kick in, and dispelling all possibility of consensus.

It's in this space that the paranoid class can breed. Bloggers about
bloggers and journalists about journalists and pundits about pundits
have found their home criticizing their tribal counterparts. Narrative
can always be news, and news is always narrative.

In most professions, journeymen(journeypersons?) are expected to be
the keepers of craft, for they alone possess the profound
understanding it takes to be an effective practicioner of their
trade. They might inhabit a feeling for the material--the mechanic's
touch--or a respect for time-honored processes; either of which are
hard-won by years of practice, inquiry, defeat, and
persistence. Journeypersons have honed their tools, and dug well below
the surface to discover the parts of [[post:2017-04-19-chunks.org][chunks]] that thinkers and
journeymen before them buried there long ago.

As far as journalists, pundits, bloggers, and other storytellers are
concerned, their medium, their material, their massage /is/ the
narrative. The fibers that they bend are the fibers of reality, and
the tapestry that they weave must be consistent, the rows of fiber
even and orderly, the story /compelling/.

Even as the paranoid hone their craft and become more and more
convincing, the pressure to publish quickly limits the quality of the
exploration, which in turn makes even the (supposed) inherent power of
the narrative shallow and uninteresting.

#+BEGIN_QUOTE
[O]ne understands paranoia only by oneself practicing paranoid
knowing, and ... the way paranoia has of understanding anything is by
imitating and embodying it.

-- Eve Kosofsky Sedgwick, /Paranoid Reading, Reparative Reading/
#+END_QUOTE

Just like paranoia, narrative compels narrativization in order to be
understood. Stories are best understood in terms of other
stories. Archetypes and tropes are the language of understanding in
this domain. Of course, since narrative is not an affect(??) I cannot
say that it "tries to understand" anything, except in the most trivial
sense.

This makes intuitive sense, though. Like their predecessors,
historians, poets, and other tellers of tales, the new journo caste
has only one job: post-hoc narrativization of otherwise disparate
events.

A journeyperson of the narrative art does not, necessarily, understand
the true, deep reality of whatever it is that they write about, since
they are mathematically unable to spend as much time in any situation
as their subjects--instead they possess greater and greater
understanding of what makes narrative compelling. What /forces/ a
reader to engage and sympathize, to build connections and trust. The
journalist's instinct to distill and simplify is predominantly good
for two things-- instilling the illusion of understanding in
laypeople, and insuring that they trust that understanding.

** Following the golden thread
Occasionally I've felt as though my life has had a guiding force, a
golden thread that I could pick up and follow, a pulsating golden
light laid out before me as if guiding me towards my next objective in
some sort of reality based video game.

This, probably, is hypomania. Or maybe it's a flow-state. Or maybe
it's just the [[https://en.wikipedia.org/wiki/Illusion_of_control][illusion of control]] creeping in. Control: that necessary
human illusion that imbues us with purpose and staves off
hopelessness.

The string metaphor for purpose and control crops up
elsewhere. Businesses or organizations that seem to /miss the mark/
(as if there were a target) can also be said to have /lost the
thread/, as though there is only one correct path through the
labyrinth, out of the cave, and back into the light.

Even in my day to day, though not imbued with the same inspiring
light, there is a sense that I am following a thread from place to
place. The interplay of consciousness and time coalesce into this
illusion-- a string of sense and meaning connecting events.

The trick, of course, is that sometimes we're following the thread and
sometimes we're laying the thread down behind us. Some of our
faculties work more like reflexes than consciousness, and the
interplay of those with the outside world can sometimes not be
avoided. Sometimes the world is configured with such weight that our
own inputs can contribute very little. But sometimes we can make an
effect. Sometimes our input is meaningful. Sometimes we possess actual
control.

Understanding those moments /in situ/ is difficult, but
important. Using these control moments wisely is how we make personal
progress, and mis-categorizing these moments is one of our greatest
sources of personal fallacy. The difference between reality and
narcissism is in our [[https://en.wikipedia.org/wiki/Locus_of_control][Locus of Control]], the difference between reality
and conspiracy located somewhere near the [[https://en.wikipedia.org/wiki/Fundamental_attribution_error][Fundamental Attribution
Error]].

** Narrative Reward / Conjunctive Maths

Narrative /feels/ good. The right narremes in the right places tickle
our intuition and inspire sympathetic responses in our brain and
body. We are /transported/ into the head space of the characters,
where our overactive empathy works to make sure that our emotions
reflect theirs exactly.

I think (and many others think at this distinct juncture in time) that
narrative feels /so/ good that we tend to view everything in terms of
narrative, even if the evidence is sparse that such causal
explanations are factual. Especially as our access to stories begins
to border on unlimited, and our forays into the neuroscience of
storytelling push us towards a [[http://greatergood.berkeley.edu/article/item/how_stories_change_brain][perfected]] affectual control, we will
become more susceptible to this failure.

# ** Science to back up this statement? Do research
# ** Storytelling, Hollywood

#+BEGIN_QUOTE
The narrative fallacy addresses our limited ability to look at
sequences of facts without weaving an explanation into them, or,
equivalently, forcing a logical link, an arrow of relationship upon
them. Explanations bind facts together. They make them all the more
easily remembered; they help them make more sense. Where this
propensity can go wrong is when it increases our impression of
understanding.

-- Nassim Nicholas Taleb, /The Black Swan/
#+END_QUOTE

It's a hard problem to have. Even adding details to "flesh out" a
narrative does nothing for its validity. Details interpolated,
extrapolated, any detail except those actually recorded from reality
(a difficult thing to do, indeed), actually reduce a narrative's
chance at reflecting reality.

# I'm not sure about this section either. Seems weak to have reader
# evaluate fictional statements and expect them to apply lesson
# learned to the real world. Need a better example and transitions.

This isn't some rhetorical slight of hand. This is a mathematical
truth of the universe: as you add conditions that a model, a
narrative, or a story /must/ obey, it becomes vanishingly likely. Is
it more likely that a given terrorist is a conservative? Or a
conservative with mental health issues and a gun? What about an
Islamist? What about an Islamist with mental health issues and a bomb?
Think about it for more than a second and you'll quickly come to
understand how deficient narrative, /any narrative/, is as a
predictive model.

That is, of course, not to say that there aren't constructed
narratives out there that are mostly correct-- there
are. Unfortunately, even post-hoc analysis of the events has a hard
time determining what past correctness means when attempting to
predict future events. Human beings are liable to assign causality
when in fact there is only chance, and recommend chance when the
mechanisms seem too obscure or complex to comprehend. Single, one-off
events end up /meaning/ everything, while the predictive realm of
symbols and certainty breaks down when it encounters something new.

** Narrative as abstraction / model
At the heart of it, storytelling is an essentialization of events. It
is a paring back of the human experience to its most salient
components: for every detail included we must leave out infinitely
more.

Reality, by contrast, tends to fractal off into the distance:
processes within processes, coves within coves, an infinite shoreline
if measured with enough detail. The statistical tricks that make our
consciousness work paper over some of that detail, failing to account
for abnormal variations, one off events, and unexpected
synchronicities.

The fundamental purpose of abstraction is to reduce complexity. To
pre-brain reality. To do some braining for us. Using chunks that
capture more area but with fewer details in a way that reduces the
barrier to entry for ideas. We "black box" components, machines,
processes, and other complex mechanisms, in order that we may use them
for their explicit inputs and outputs without thinking about their
inner workings.

In this same way we can view graphs, pictures, and other graphics as
purposeful simplifications. They contain a programmed output (trend
line, circle size, arrow direction) that represents a thought process
working on a programmed input (variables chosen, data gathered,
processes designed). The image becomes a model of reality, complexity
abstracted away, what's left now simple and workable enough for higher
level enjoyment.

What do they say, a picture is worth a thousand words? In these words
I've got four charts worth of abstraction alone. Words are
abstractions too. Whatever we, as authors choose to write, there are
uncountably many more words that haven't been written about the same
subject. The choice of words is statistically a matter of exclusion,
not inclusion. Words become models for concepts and stories become a
sort of meta-model, over-arching concept, order of display.

The narratives that we write become black box operators for
classifying future events. Events (inputs) are inserted into the
narrative, and out the other side come interpretations of those
events. With some preparation the inner workings of narratives can now
be forgotten to reduce cognitive load.

# Interpretive lens (hermeneutic of suspicion from Ricoeur)

#+BEGIN_QUOTE
The so-called "scientific view of the world" based on this can hardly
be anything more than a psychologically biased partial view which
misses out [on] all those by no means unimportant aspects that cannot
be grasped statistically.

-- C. G. Jung, /Synchronicity: An Acausal Connecting Principle/
#+END_QUOTE

Similarly, reality can be measured however you'd like. Correlations
can be found wherever you look, and coincidence is not far behind.

A single human being's conception of the world, this accidental
narrativization, is as one giant Texas Sharpshooter fallacy. The
bullets fired, the barn hit, and nothing yet left but to draw a
target. As Nicholas Taleb and other financiers are wont to say, you
have to be drunk or blind not to find a pattern in randomness.

Donald Hoffman has been making the rounds, claiming to know that
reality is nothing close to how we perceive it. I don't know that this
is quite right. I think a more compelling case can be made that
reality is nothing close to how we /interpret/ it. Maybe this is just
sophistry, but it's worth the typing.

In one of his talks, Donald Hoffman knowingly [[https://youtu.be/6eWG7x_6Y5U?t=9m28s][flashes]] us a picture of
some beetles swarming a bottle, confused by its shiny, dimpled brown
surface, and believing that the bottle is an incredibly large, fit
mate. Donald quips that we humans have somewhat more discerning taste
in women, that at least we wouldn't be duped by such a simple ruse.

We don't swarm bottles accidentally, but aren't we turned on by
animated depictions of anatomy? It's clear that a two-dimensional
representation of sex characteristics can send our mating instinct
into a frenzy. It's clear that what we're not so much attracted to
viable mates, but to the characteristics that /signify/ viable
mates; the /symbols/ that cause us to load our mating chunk.

Is video, from a complexity standpoint, so much more different than a
bottle that we can claim to be immune to such tricks? Doesn't makeup
fool one's brain into believing that certain sex characteristics are
present when they are not? I even bet we'll find sex robots (or
virtual reality sex as in the just-alright movie The Zero Theorem)
more universally satisfying in the future, as their symbology moves
out of the uncanny valley.

Human beings are aware, /consciously/, that these things are
facsimile, but /subconsciously/ fall for the same tricks. Can we say
that it is our perception that is broken? Doesn't perception happen in
the conscious realm? What about our subconscious taints our
interpretation such that it's clear we interpret exactly nothing about
the world entirely correctly? If hermeneutics and criticism are
attempts at moving our interpretive mechanisms into the /conscious/
realm, how can we make sure we do so effectively? How do we avoid the
attribution errors and other biases that taint so much?

If it's our interpretation, our analysis, our /narrative/ that's
broken, inherently, /evolutionarily/, then we must be ever more
vigilant against the creep of grand narratives that might sweep us up
and into fervor. It's not the dimples that deceive us, and it's not
the shiny brown, but all of life is its signifiers, fit into our
narrative -- our understanding of the way things are.

** P-hacking
In light of this, I can't be convinced that all scientists that
"P-hack" understand that they are doing something wrong. They're only
messing with the fundamental constituent parts of reality,
anyhow. They're only tripping face first into the gaping chasm that
lies between perception and interpretation.

The reality is that if you ask enough questions and gather enough data
you [[https://fivethirtyeight.com/features/science-isnt-broken][will]] be able to find a pattern. You /will/ be able to draw your
target and announce your conclusion.

Good science(confirmatory and disconfirmatory science) can only be
done when the target is drawn before the data is collected. It would
be better to regard studies with many measurements as reality surveys,
and analyze them with the eye of the financier, because if a narrative
is given the data reality will have no choice but to conform.

Of course, drawing a target is a matter of philosophy ("what does a
measurement /mean/?"), so confusion is understandable. Maybe this just
means that we should tinker and refuse to worry about it. I don't
know.

Statistics are counter-intuitive enough that they can beguile even the
educated, and they frequently allow bias to fester.

** Paranoia as defense
A cruel world demands justification. "Senseless" world explanations
are inherently unsatisfying. The paranoid reading of reality, one rife
with grand intentions and even grander conspiracies, appeals to the
sensual nature of existence.

#+BEGIN_QUOTE
We spend our entire lives trying to tell stories about ourselves--
they're the essence of memory. They're how we make living in this
unfeeling accidental universe tolerable. That we call such a tendency
"the narrative fallacy" doesn't mean it doesn't also touch upon some
aspect of the truth.

Some stories simply literalize their metaphors a bit more explicitly.

--Ken Liu, Preface to /The Paper Menagerie/
#+END_QUOTE

Paranoia, as Eve Sedgwick says, is the most ascetic form of love. It
demands little from its object, but grants it much attention and
affection.

#+BEGIN_QUOTE
The first imperative of paranoia is There must be no bad surprises,
and indeed, the aversion to surprise seems to be what cements the
intimacy between paranoia and knowledge per se, including both
epistemophilia and skepticism.
...
No time could be too early for one's having-already-known, for its
having-already-been-inevitable, that something bad would happen. And
no loss could be too far in the future to need to be preemptively
discounted.

-- Eve Kosofsky Sedgwick, /Paranoid Reading, Reparative Reading/
#+END_QUOTE

Eliminating surprises works well when you have a relatively finite
number of worries.

My intuition is that such paranoia in the modern world is
self-defeating. It pays to fear and to protect yourself from wild
animals or other small tribes. Not so much from giant governmental
mechanisms that can kill or silence you in a thousand ways. Not so
much from the perceived threat of 8 billions of other humans connected
to each other via the series of wires and tubes we call the internet.

So please, by all means, fantasize about conspiracies for fun. Love
the drama of life a little bit. But understand that putting money or
effort into such things is gambling -- playing a lottery you're
unlikely to win.

** Paranoia without identity groups?
I don't know who you direct your paranoia at if you don't have a sense
of tribal identity. Our collective identities serve as the objects in
our narratives, the agents and injured parties, all. I don't know how
you have tribal identity without paranoia.

I also don't know if paranoia exists without tribal identity. Who do
you fear? What must you uncover?

How do we decide what parties to trust? Not in a an "honesty" sort of
way, because we can still ultimately trust many of those that are
dishonest to us, but existentially. What other agents do we put our
trust /in/ without the aid of identity?

Even the simple matters of context and subtext are rooted in
identity. How do we /even understand other people/ if we don't have
groups to fit them into?

** Reparative Methods
I don't like to be prescriptive. I don't think that there's any one
thing or few things that can be done to fix the state of
discourse. Still, I'd like to offer suggestions from my own brain. A
few of my own interpretive tools for building understanding from
diverse source materials, including materials from those people that
you would generally be disinclined to believe. It's tricky.

#+BEGIN_QUOTE
The vocabulary for articulating any reader's reparative motive toward
a text or a culture has long been so sappy, aestheticizing, defensive,
anti-intellectual, or reactionary that it's no wonder few critics are
willing to describe their acquaintance with such motives.

-- Eve Kosofsky Sedgwick, /Paranoid Reading, Reparative Reading/
#+END_QUOTE

The simplest technique is to simply ignore the bad bits of academic
text. Most people ignore irrelevant words almost constantly, and
extending the favor to our philosophical enemies is the least we can
do. Ignoring items you disagree with opens you up to the possibility
of finding some text that speaks to you, and allows you to focus on
the ways that you are alike, rather than different.

This is your least effort option, but it's not practical for many
situations. Mostly our differences are important and must be
addressed.

# Might need more research for anarchy connection
The next step, then, is to engage in dialectic. The assumption that
discussion carries mutual benefit is foundational to many reparative
methodologies (family counseling, anarchist micro-government, etc),
and is easily applied to our reading habits. Dialectic moves shared
reality, debate encourages us to pit ideologies in some sort of
winner-takes-all gladiator battle. Is ideology a slave in this
metaphor? Couldn't tell you.

Regardless of our adoption of ideas from any person or text that we
engage in dialectic, we can learn something nonetheless. We can learn
the /what's/ and /why's/ of other ideologies. We can understand the
possible of other internally consistent narratives. Maybe by
understanding the fractures and breakdowns of other ideologies we can
more accurately pinpoint the fractures and breakdowns of our own--
places where we can ultimately choose to employ other systems of
thinking that are more situationally effective.

These unintended consequences are the /side effects/ of ideas. Just
like in medicine (a purely Talebian example), in philosophy progress
in made most often by tinkering and finding the unexpected. Like
Viagra (invented for cardiological disorders), the side effects of
ideas we invent or encounter may be the primary effects we seek in
another domain.

Even acting's time-tested method for keeping a scene going, the
classic "yes, and?" allows for more ideas rather than fewer, and could
be considered a reparative technology. I don't know.

# contextless reading (reading without knowledge of the author, time, or place)

How often do you read something interesting and then go searching
around for the political leaning of the author before deciding whether
the text should be taken seriously? Is it worth it? What signals have
to be present before you'll trust something?

Sometimes I think the real alternative to narrative is to communicate
entirely through the visceral emotional impressions of non-verbal
sound and aesthetic imagery in the way that Andrei Tarkovsky
mastered. Sounds cool at least.
