#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Seems Absurd
categories: attempts
---
#+END_EXPORT

* Seems Absurd

Given the complex nature of reality it would seem absurd to say that:

- There is only one axis of oppression
- There is only one hierarchy by which class is determined
- All members of a single race share class characteristics
- All members of a single gender share class characteristics
- There is only one path towards progress
- All technologies (machine or thought) that are old are bad
- All technologies (machine or thought) that are new are good
- All of our current instruments for determining progress are correct

Simple-world interpretations are bound to fail outside of contrived
circumstances. If the world seems simple it is because evolution
couldn't evolve senses around phenomenona that are unpredictable,
inconsistent, and otherwise uncomputable.

With that in mind it seems likely that:

- A person can be oppressed by many (perhaps unknown) axes of oppression
- A person's class is determined by a complex juxtaposition of (perhaps unknown) hierarchies
- The racial component of class is not deterministic
- The gender component of class is not deterministic
- Progress is available through at least several (perhaps unknown) paths
- Some old technologies are still good
- Some new technologies are bad
- We have no way of reliably knowing which is which

Groups of people can(sometimes) act as a baffle between the world and
this uncertainty. Ways of thinking and knowing that are disparate can
find a synergistic average that makes the most of doubt and knows more
than any individual human.

That is, /if/ you manage to find a competent leader(or set of rules?
or algorithm?) that can synthesize that collective thought into
action.

Of course, groups can know less than particular individuals as well. A
group like this would have broken metrics, perverse incentives, or
heavy shared information bias. Of course our tools for evaluating
these things are also broken.

It is unwise to maximize for any process except that which allows for
the greatest plurality of well-intentioned individuals to commune and
refine their positions.

# This looks a lot like what Hayek says is the function of "pricing"
