#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: wide
title: Notes on Matter and Zeitgeist
categories: misc notes
---
#+END_EXPORT

* Notes on Matter and Zeitgeist

Sitting here tonight and noticing, aimlessly, that I have some descriptive work to do that is not going to get done anytime soon. I've been focused on longform writing and the pressure to create complete attempts, rather than attempting slowly, over much time, is tiresome. Working slowly, over much time, is equally tiresome. I don't know.

In [[post:2018-04-07-ai-from-a-different-computer-universe.org][AI from a Different Computer Universe]] I labeled a large blank area the "substrate of patterned matter and zeitgeist" as if that alone were explanatory. I'd like to compile some other partial descriptions that may be benificial to my own thoughts about the thing (if they're in one place).

** Substrate?
I'm talking about fundamental building blocks here. It feels weird to say that things are "literally made of goals", so I probably won't. I will say that we behave /as if/ this were true, so when I say that the region is a "substrate of patterned matter and zeitgeist", I mean that for a mind (whatever mind it is I'm in the process of describing, universality not guaranteed) to work it must also behave /as if/ everything were made of both matter and value (goals, zeitgeist).

** Patterned Zeitgeist

Zeitgeist is [[https://meaningness.com/pattern][patterned]] because it has some predictable forms. It is difficult ([[https://wiki.lesswrong.com/wiki/Narrative_fallacy][or too easy]]) to describe because it is [[https://meaningness.com/nebulosity][nebulous]]. In [[post:2017-10-19-goal-plane.org][Goal Plane]] I state explicitly that there are things that happen within Zeitgeist that not everyone can sense, or that appear to have different shapes from different angles.

One universal seeming pattern is that forms within Zeitgeist (the goal plane) can affect the material plane, and forms within the material plane can affect the goal plane.

Partial descriptions of the push and pull with material reality:
+ [[post:2017-10-19-goal-plane.org][Goal/Zeitgeist]]
+ [[https://en.wikipedia.org/wiki/Actor%E2%80%93network_theory][Actor-Network Theory]]
+ Popper's [[https://tannerlectures.utah.edu/_documents/a-to-z/p/popper80.pdf][World 3]]
+ [[https://en.wikipedia.org/wiki/Noosphere][The Noosphere]] (kinda weak?)
+ Some of the [[post:2018-09-08-notes-on-fundamental-meaning.org][fundamental meaning]] stuff I was thinking about recently
+ [[https://hermetic.com/bey/taz3][Temporary Autonomous Zones]], [[https://en.wikipedia.org/wiki/Egregore][Egregores]], [[https://suchaone.github.io/blog/tulpas.html][Tulpas]]

It also seems as though Zeitgeist has dimensionality to it (I often think of it topologically (though I'm much too dumb to get into the weeds about specific topological forms)) that can be [[post:2018-09-05-movement-in-the-goal-plane.org][navigated]] similarly to the material world, and has regions[we'll see about that] that feel distinct and that have their own traits.

Partial description of the Zeitgeist "landscape":
+ The "surreality" of meaning that we live in ([[https://books.google.com/books/about/The_Passions.html?id=TCAUagXFG4sC][Solomon]])
+ [[http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199235018.001.0001/oxfordhb-9780199235018-e-16#oxfordhb-9780199235018-bibItem-667][Moods]]
+ [[post:2018-09-05-movement-in-the-goal-plane.org][Plans]]
+ Also the TAZ, Eg things, and Tulps as above

Noticing that the psychic groupings are in both listings, maybe that's the obsession with them? They affect the world and they're "big" enough that many people can agree that they exist. Sounds like a good start at least.


** Patterned Matter

Content to say that it probably exists

------------------------------------------------------------------------

/This document will grow as I continue to galaxy brain/
