#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: wide
title: Notes on Fundamental Meanings
categories: misc notes
redirect_from:
    - /notes/misc/2018/09/08/notes-on-fundamental-meaning.html
---
#+END_EXPORT

* Notes on Fundamental Meanings

** I.
I was talking with [[https://twitter.com/cognazor][Jason Snyder]] and we had a minor disagreement about the role that symbols (in this specific case, language) play in the course of our thought. We video-chatted and were able to discuss, and I think we're on the same page. What follows were my initial thoughts, now watered with Jason's cerebrospinal fluid.

** II.
I think identifying symbols as the fundamental unit of thought is somewhat misleading, like thinking that metaphors are stored in the words that one uses. In my piece [[post:2017-04-19-chunks.org][chunks]] (from many moons ago) I tried to explore the structure that I feel like thoughts rely on. They seem to me like a bunch of sorta fuzzy buckets or a mental geography of ideas that get retrieved together.

Loosely related to this is the "ground beneath thoughts" which I think is experienced vividly through these things: (not nearly an exhaustive list)

Thought opening up to reveal "ground":
+ [[https://en.wikipedia.org/wiki/The_Doors_of_Perception#Synopsis][Visionary experience]] (as Huxley)
+ [[http://www.rigpawiki.org/index.php?title=Pure_perception][Pure Vision]] (as Vajrayana)
+ [[https://en.wikipedia.org/wiki/Kensh%C5%8D#Contemporary_accounts][Kenshō]] (as Zen)
+ [[post:2017-03-01-travel-blog.org][Salience]] (as me)
+ [[https://en.wikipedia.org/wiki/Defamiliarization][Denaturalization/Defamiliarization]] (as the postmodern tradition)
+ [[https://en.wikipedia.org/wiki/Aletheia#Heidegger_and_aletheia][Disclosure]] (as Heidegger)

Partial descriptions of the "shape" of "ground":
+ Ineffability
+ Unflat (as [[http://spinweaveandcut.com/unflattening/][Sousanis]])
+ [[post:2017-10-19-goal-plane.org][Goal]], sorta (also as me)
+ To "[[https://en.wikipedia.org/wiki/On_Certainty][know]]" as in to "know" that there is a tree there, or to "know" that one has two hands (as Wittgenstein)
+ [[https://meaningness.com/meaningness][The Complete Stance]] (as Chapman)
+ [[http://arobuddhism.org/community/form-emptiness-and-non-duality.html][Emptiness]] (as many Buddhisms)
+ [[https://en.wikipedia.org/wiki/Flow_(psychology)][Flow]] (as positive psychology)

** III.
I think my current thoughts problematize some of /these/ things:

+ Brain as separate from self (othering the unconscious, as if it does not speak to us)
+ View of thinking as inseparable from symbols (better, in my opinion, to see symbols as another model approximating thought)
+ View of meaning-making as entirely within our control /or/ entirely without (as though it were that simple)

And to address them we can start here:

+ Sensation of things "As they are" is very real
+ Personally late developing internal monologue seems to imply cogitations without "formal symbol"
+ Experience of [[https://www.quora.com/What-is-your-inner-monologue-like-and-how-do-you-interact-with-it-and-or-quiet-it][some people]] as "handing information to their brain" via the internal monologue is also weird
+ Aella's experience of the "stones" of her thought as being further apart after the use of [[https://twitter.com/cognazor][psychedelics]] (what is between them?)
+ Things often feel most "meaningful" when symbolic reasoning drops away


** IV.
Lastly, weirdly, my first thoughts were:

"/Nice. I would just add that language also modulates how we think and make meaning. ‘Your’ meaning is impossible without internal semiotics./" - [[https://twitter.com/cognazor][@cognazor]]
+ "Modulation" is definitely the right word - the [[https://www.youtube.com/watch?v=VIg5HkyauoY][color blue]], while not /necessarily/ impossible without the word, is a much duller experience without it.
+ "Impossible" seems like exactly the wrong word. Model-making and thinking in metaphor require symbolic system, but the signified parts are embodied and without symbol. These embodied things still have a "patternicity" that is anchored in a push and pull with the real world, but to identify them as symbols in the same realm of language seems limiting.
+ It is from embodied meanings that we trace thoughts into the flat representations that become words or images.
