#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Movement in the Goal Plane
categories: attempts
---
#+END_EXPORT
* Movement in the Goal Plane

/This document is slightly more under construction than the other ones right now, just so you know./

There's been something missing from my discussion of [[post:2017-10-19-goal-plane.org][goal]]. Mainly, I think, one wonders how we get from a vague conception of motivation, utility, or goal to an actual sequence of actions. If the perception of goal is somewhat akin to our perception of physical reality, if our perception of physical reality is in some senses evolutionarily subservient to our perception of goal, and if neither type of perception provokes action directly but instead informs strategies, tactics, and /plans/ then aren't we missing something when we talk purely of perception? Aren't we obligated to talk about the plan-making step cogently as well? After all, what good is a perception without an accompanying action?

This is apparent when we see perception as instrumentalized for the sake of goal. As Heidegger, we cannot understand an object simply by describing it. We must experience an object if we wish to disclose its true nature.

To get anywhere I'll assume that the glue that holds together perception and action is cognition. I must be careful with this definition, since the line between perception and cognition remains fuzzy, but that seems alright. Much of what we think of perception is already the brains interpretation of the raw signals anyway. These interpretations can be hijacked via illusion or medication just as easily as cognition can be hijacked via deception. Reactions can also happen in parts of cognition that are hidden from the conscious mind. Ingrained habits and muscle memory take the wheel when expedience is the dominant factor, and "miracle" solutions to tough problems "pop up" in our minds as if by magic.

That's not too say that some of the magic can't be quantified, however. [[https://osf.io/56ja2/][Planfulness]], in recent formulations, is a combination of three factors. The mental flexibility to decide actions that interact with a particular goal, the formulation of distinct cognitive modalities for each goal, and a temporal orientation in which the "distance" to a goal is evaluated against current positioning in time, space, and goal. This formulation seems compatible with my own.

In our brain, "decision" might be the broadest stroke of a plan. Given our temporal orientation and a particular required modality we decide on an action. Underneath decisions are revisions?  Instantaneous modifications of a given decision? We must also decide when to "undecide" something that is no longer working - which may be a function of sadness? That feeling in your stomach when you have to give up on a plan that you thought would work?

Anyway, we hope that as humans we can (mostly) make some sort of progression between /perceive/, /plan/, and /act/, even if machinations between them remain mostly hidden from our conscious self.

Chapman and Agre have already [[https://www.sciencedirect.com/science/article/pii/S0921889005800260][done]] some of the work for us while thinking about AI in the late 80s. Their conception of a /plan/ is as a sort of natural language communication of a heuristical sketch -- the sparsest framework of directions that get you from point A to point B through a complex world. This is like a recipe, where there is information stored /outside/ the plan -- information about how big the pieces of vegetable should be when chopped versus diced, information about an individual oven's hot spots, temperature tendency, and more. If the recipe were to contain all of this information it would be too dense and complicated to be joyfully followed. The recipe instead describes a goal, and provides hints about how physical reality is interacting with that goal.

The vague recipes of the technical challenge round of the [[https://en.wikipedia.org/wiki/The_Great_British_Bake_Off][Great British Bake Off]] are a fun illustration of the downsides of the trade-offs. With instructions like "prove", "make a sponge", or "bake until done" /vast/ amounts of information are outside the plan -- though the recipe is still very legible to experienced bakers.

The sparsity of human plans is often a feature, not a bug. Words are, at best, a temporally locked trace of a particular thought pattern. A single frame of a continuous animation. Plans that are made of words are subject to the same definitional limitation. A good plan circumvents this by using specific words where context is unlikely to vary, and vagueries where a plan's conception must rely on loose patterns rather than absolutes. In a good plan you hardly even realize that you're relying on your own adjudication -- the details are clear even if they're not deterministic.

Ultimately plans conceived in this way are a series of translations from world knowledge, goal knowledge, and self knowledge, to a plan that is as vague as possible, to a precise moment to moment plan, to action in the world.

Perception of Goal \to Conception of Plan \to Actualization of Action : A collapse from many possible truths to a single one, from many possibilities to an actuality.

Let us take the (non-human) example of "Continue Along the Road" issued to a self-driving car. It is a command that needs to be situated in the context of the street (external geospatial knowledge) and codified driving rules (external legal and social convential knowledge) before action takes place. If there is no method by which a car can "legally" continue, it must determine some other action until the option is available to it. The command "Turn the wheels to the left now" is more specific, directly relates to the cars mechanisms rather than outside context (though "left" is technically outside knowledge), and is temporally instructive and non-malleable. It is also less flexible, and when undertaken will have immediate consequences.

As such, our planning is somewhat like the "extreme late binding" conceived of in the programming language [[https://en.wikipedia.org/wiki/Smalltalk][Smalltalk]] - wherein it is not until context can absolutely be confirmed that the granularity of the instruction "drops down" to immediate action.

Pedantry is perhaps a failure of this late binding process, the inability to understand the level of granularity that a particular plan requires. An insistence on "sticking to the books" is a misjudgement of when and where the external knowledge is valid or useful.


-----------------------------------------------------------------------

If we are now conceiving of two planes of existence, one the realm of thoughtforms and choices([[post:2017-10-19-goal-plane.org][goal plane]]), and the other the realm of matter and energy([[https://pathfinderwiki.com/wiki/Material_Plane][material plane]] lol), then progression through a plan is movement in the goal plane. Each step towards the end of a plan is literally a step towards /a/ goal and through /goal/. I've said that it is somewhat harder to change or move about in the goal plane than the equivalent movement or change to the material one. Perhaps this illustrates why. If, say, one needed to walk all the way across town to buy groceries, one might say that although the physical distance covered during their walk was quite large, the movement through goal was quite small (since our quotidian goals are not our overarching goals (although being on the verge of starvation would significantly alter that)).
