#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Sensations for Emotional Reasoning
categories: attempts
---
#+END_EXPORT
** Sensations for Emotional Reasoning

*** You in Need of Release
You, tightly bound, in need of proper release, cords cut, returned to freedom. Assuming that the mind is of leather straps or metal catches, it follows that the straps must be released and the catches undone for free movement to occur. Assuming that the mind is a pressurized pipe, or maybe some other vessel, it follows that we must occasionally "vent" or "blow off steam". Assuming that the mind balances upon a single point, it follows that occasionally things fall "out of balance" or are "unbalanced". A mind of rope may be in "tension" or "relaxation". A mind of doors may become "unhinged". But where does the pressure go? What straps are released? What direction does the brain tip to become unbalanced?

*** You Who Might Not Know Your Emotion as Friend
Are you your emotions? Or do those emotions whisper to you? Do they whisper sweet secrets of your innermost desires and motivations? Are you your motivations? Or maybe, because your emotions must whisper motivation's secrets to you, your motivations are somewhat outside of you as well.

Here we are in today's metaphors: desire, like reality TV, dozens of suitors from across space and time. Emotion, your best friend, informant to your cause, purveyor of juicy gossip. What do you believe? Who do you choose? Ultimately that's up to "you". Maybe you believe that your best friend's opinion must be your own, though I find that unlikely. And maybe you believe that whatever suitor is strongest should just take you, by force. I find that even unlikelier. 

*** You Who Might Be Blocked or Clotted
Let us forgive what I said about ropes. Your life is a rope that is slipping through your hands. The occasional clump, snarl, clot or blockage catches upon your palms and interrupts the gentle slither of fiber on flesh. Pain! Frustration! Suffering! This is not far from the truth. You slow your breath and widen your grasp and become an accommodating channel for the rope, where the clots might pass you by, noticed but evaded. This seems wise.

But maybe there's something else. Maybe with effort you can transmute the *clots* or *blockages* of your suffering into *knots*, sturdy affordances by which you can grasp the rope and let it pull where it may. By this you relinquish control and establish it. It is by your own grip that you hold this particular knot, having skillfully allowed less appealing forms to pass unmolested. If you are not accustomed to a firm grasp the knots may very well seem like a nuisance, a kink to be unwound. This seems unwise.

Let go of the rope, you say? The gentle float is worthwhile, but mind your lifeline to past, present, and future. 

*** You Who Feels Nothing for the Moss and the Rocks
Are you filled with emotion at first glimpse of raw earth? Do you chuckle when you avoid a puddle? Or perhaps when you barrel through?  Mostly not. But what of when you slip and fall, or the going is slow and harrowing, or the puddle means rain after a long drought? A tree might appear neutral on first appraisal, but how does it feel to have shade to sit in? One wonders if that emotion was there the whole time: not in the fibers of the tree or water of the puddle, but in how those fibers and that water interact with what we can or must do in the world.

*** You Who May Not Feel the Emotional as Physical
The moon is not as big as it may appear near the horizon. Our vision stops when our eyes remain still. Hills appear steeper when we're sad. Glasses of water appear larger when we're thirsty. The world is not our sight or our hearing, though that is a part of our world. Our world is not the "surreality" of emotion, though the surreality is part of it. 

As much as any of our "physical" senses of the world belong to us, so does emotion - our sense of motivation, of goal, of value. Without emotion there is no world out there: our senses co-evolved to fill our niche. We can not see without seeing what something means to us— our motivations in the landscape.

...and what of these motivations? From whence do they come? Do they come from yourself? A genetic realm beyond your sight (and within your emotional gaze)? Do they come from without? A societal miasma beyond your sight (and within your emotional gaze)?

*** You Who Might Need a Conclusion
The path you might wind through the world of desire is infinite. You may well wear your walking shoes.

Try to imagine where your emotions come from. Are your emotions a "thing" on their own? Do they exist without the context in which they operate? Have you ever been angry about being angry? Who are you angry at, then?

Try to imagine how your emotions pull you. Think about catching a knot and holding tight. What does it feel like to be pulled along by anger? Or by sadness? Or by happiness? Are there memories you had to conjure in order to inhabit this metaphor? Is there anything tugging on you now?

Try to imagine three reasons why you're reading this. Did you make them up? Were they latent? How small were they? A pebble in your mind's eye? Or did you look up and into the face of a cliff?

*Take this, a gift:*

1. Emotion is an adaptive feature of our existence; even the "negative" ones have positive purpose
2. Emotion holds the meaning of our lives, or as close to it as we can get; even when this meaning is ill matched to our new reality
3. Emotion is not who we are in the world or what we do in the world; it is something that precedes those things.
4. Emotion is not something we choose; it is something that we choose to respond to, however we may
