#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Five Minutes of Dangerous Writing
categories: misc
---
#+END_EXPORT

* Five Minutes of Dangerous Writing
/Used [[https://maebert.github.io/themostdangerouswritingapp/#/][The Most Dangerous Writing App]] to force some words out into the world. Written in one 5 minute session and left unedited./

here's a thing, perhaps I will be saved by my lack of typing skills, since backspace seems to keep the timer ticking. The flow of words from my brain seems a little forced, but for five minutes I can see how my brain would not yet go blank. It is not as if I am being witty, I am simply dumping words onto the page in hopes that they do not go away. A weird sensation. Normally I do not know whether I would care whether or not the words go away, since normally my thoughts go aways regardless. Maybe the energy of typing them into the web page is what gives them value, since my fingers and wrist are liable to twinge from the extended effort. That makes me think that I really should investigate alternate typing modalities, since 5 minutes doesn't seem like the longest time to be continuously typing words... maybe I will rekindle my interest in stenography... after I complete the three million other things I've signed myself up for this season. I really do have too many hobbies. Too many vocations, even. Called in all directions with no where, ultimately to go. C'est lal vie, I suppose.
