#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Sensations for Wordsmiths
categories: attempts
---
#+END_EXPORT
** Sensations for Wordsmiths

   I've struggled to keep up any sort of blogging habit. Mostly this is just because I don't have anything to say. Partly though, it's because words suck. Or so I've heard.

   Words are hard. Words are inadequate. Words are inaccurate. Words are fuzzy. Words don't fully capture an idea. Words are the worst. We just don't have the words for it. There is no english equivalent to this word. There are no words to express things. Words don't capture reality. Words barely mean things anyway.

   It seems most peoples' model of the way words work is as some sort of transmission from one brain to another that's lossy or inaccurate due to some feature of the words that the person chose. That's pretty optimistic.

   In some peoples' model words have local valence, and, while accurate within a bubble, are easily misinterpreted by those outside. Okay, but still.

   People tend to think of words on the internet, or words in a book, but ignore folk uses of words. This lands them far from the truth. Words mean things because they're pointed at things besides other words.

   When we're talking to the people physically around us these things are almost always the shared environment. Weather. Friends in common. Clothing. Words that appear entirely contentless without their social situation. We say observations until it looks like we share a single reality.

   When we're working together to accomplish a task the words often refer to configurations and immediate context. You lift that side. Am I moving or are you? Look in the hole. I'll go high, you go low. Words that appear entirely contentless without their surroundings.

   These "contentless" words (though maybe here I might /actually/ call a word "lossy") mean real stuff. Words on the internet? Words in books? Concepts??

   Words point /through/ some conceptual domain at an actual reality. Words change sounds, concepts change content, and reality literally moves beneath your feet. A rose by any other name would still be a rose?

   [[tweet:https://twitter.com/rfinz/status/1036644042694709248]]

   To borrow from my own [[post:2018-09-05-movement-in-the-goal-plane.org][words]]:

   #+BEGIN_QUOTE
   Words are, at best, a temporally locked trace of a particular thought pattern. A single frame of a continuous animation.
   #+END_QUOTE

   Words are pattern poetry, chorded activations of concepts that bring us close to some framework of understanding. Just framework, though—bones.

   [[tweet:https://twitter.com/literalbanana/status/1150357498274041856]]

   You don't need words to think, though the framework that words provide may help scaffold you into more complex domains. You don't need concepts to think, though concepts may help scaffold you into a domain that resembles words.

   So words point through concepts that you possess, and are adequate to express those. Well, mostly adequate. Words don't smell. Words don't sing. Words don't rearrange matter with their bare hands. I just don't even know if inadequate is an adequate word to describe the not-even-wrongness of words not singing or smelling. They're not inadequate. They're nonsensical. Or maybe seussical.

   Words also point through concepts that other people possess, and are adequate enough to express those — confusing as that may ultimately be.

   So do words suck? Are words hard? Or what?
