#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: wide
title: Why Knots?
categories: misc
---
#+END_EXPORT

* Why Knots?

(lightly edited from direct messages to [[https://twitter.com/cognazor][Jason Snyder]] 8/6/2019)

** The perfect knot:

- exists for a purpose
- accounts for the materials in which it is tied
- unties exactly when its usefulness expires
- binds two ropes together as robustly as if they were one, or binds a rope to a fixed point without compromising the strength of the rope
- either passes through a block without snagging or will /not/ pass through a block, depending on the knot

** The imperfect knot:

- forms without intention
- pays no heed to the particulars of its material
- is difficult or impossible to undo
- cannot be counted upon in its security
- reduces the strength of the rope in which it is tied
- will snarl in the block

The knot becomes an exacting metaphor for a way of holding emotions/concepts/attachments/reality in general:

firmly, 

with an eye for the particular, 

until the exact moment they are no longer useful, 

in a way that slides when necessary and grips when it is not.

So, the transmutation of a clot or snarl into a thoughtful knot (knotted cord also having some previous sacred associations) is a total transformation into an impermanent but useful affordance in the thread of life, that can be gripped, clipped in to, undone in a moment, used to take up slack, used to produce slack, whatever else our life may need help in its arising.

Still, it implies some skill in the transformation, since the imperfect knot looks an awful lot like a clot or snarl...
