#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Mess Made Real
categories: attempts
---
#+END_EXPORT
** Mess Made Real
I am so beside myself that words feel empty. Forget the hypercomplexity of global objects, the concerns of a middle-sized metropolitan area are humbling enough. There is no epistemology adequate for this local, within-walking-distance set of events.

[[tweet:https://twitter.com/MutualArising/status/1266197206538870784]]

One person: people die every day, but not this way. It's not escaping justice: people escape justice everyday, it's that escaping justice seemed inevitable.

A grocery store: a piece of essential neighborhood infrastructure whose absence is a distinct source of inequality, a capital asset of a large corporation, an employer in an uncertain economy, full of "stuff" not people, stuff that feeds people that the neighborhood is now already fundraising to replace. 

A housing development: neighbors for more neighbors, income for local businesses, just a bunch of lumber, a gentrifying force.

A big-box store: ugly, discriminatory, insured. A hole on the strip that will take years to rebuild in any form.

Small businesses: complicit, an acceptable casualty, just stuff, a person's passion, several peoples' livelihoods, the only liberatory capitalism. Signs in the window: "black owned business"—passover, reckoning.

Policing: tremendously overfunded, tremendously unprepared to handle any sort of significant resistance. Are people really just finding out now that a crowd as small as 20 people can loot a store without significant consequences? What was preventing them before this moment?

Protest: "stay home tonight" he said, like we were speaking to god. "do something" he said, assuming we were just walking to enjoy the evening

"just a few broken windows" → "looting essential items, mostly" → "a little light arson" at extraordinary speeds

Rioting: necessary convulsion, we trust it will stay contained to property, trust that the revelatory freedom will respect the right to life of the people around it, trust that the already activated can't be goaded into more extreme actions, trust that the worst of us won't take advantage of a bad situation to harm the worst off of us

Startling insensitivity from police on the streets (or the rooftops, as it were). "Less-lethal" munition fired without care for life or limb, actively "drawing aggro" like they were in a video game. 

Startling silence from anyone that seems like they could be in charge. No leaders on the ground. Nobody at the top putting their bodies on the line. I can't blame them. I haven't either. But the symbolism of me yelling at a cop pales to the spiritual relief of a Mayor or police chief subjecting themself to the abuse of the crowd. Seems like the one thing disincentivized by modern politics is actual leadership.

Restrained by precedent, restrained by fear, confused by the speed at which the goalposts move. 

Community leaders imagining that the whole city is their community, elected leaders imagining that consistent messaging works as crowd control.

Me, trying to water my tiny garden and keep the new transplants from dying.
