#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Anxiety is Effective Action Failing to  Leave the Body
categories: attempts
---
#+END_EXPORT
** Anxiety is Effective Action Failing to  Leave the Body

At this point whether I'm Newton in quarantine or a self-care expert, the data is in: my body would rather buy prospective hobby gear or spend 12 hours failing to debug nebulous errors buried under n+1 layers of library code and operating system peculiarities than to practice any of the things that exert influence on or receive feedback from a meaningful outside world.  What a devastating thing to learn about oneself. 

And that observation was from before the uncertainty of social uprising, the tradeoffs between immediate security and long-term improvement, the financial precarity of my own life and the financial precarity of the people and communities I love made extremely more apparent.

Seeing ambitious projects spring to life and immediately crumble under a tragic commons is wrenching. The radical seems synonymous with the immediate, but the more of these projects that fail, the more it seems like immediacy only works within the most intimate organizations of humans. 

Conversations with friends about hard topics feel equally likely to entrench, to frustrate, or to exhaust. A number of friends are now conspicuously absent from the internet after spending weeks boosting info and sharing links. The clarity of the moment has faded, exhaustion, confusion, and concern about the implementation details have emerged as our primary modes of online interaction.

At this point it really feels like my actual sphere of influence is the garden bed I could build, the plants I can tend to, the dog I can feed, the people I can love.

But that's the thing, right? Our points of leverage are often nebulous to begin with, and it takes a certain amount of storytelling to convince ourselves that we have any leverage in the first place. The things that it's easy to see ourselves influence are the things that we have always influenced, since the dawn of time. We're adapted to see those things. 

We're not adapted to know how yelling at a crowd or volunteering for a large organization or working at a large company actually do anything.

Anxiety is the sensation of a threat to our goals or values; if it's in our values to be helpful, good, or useful, then simply being unable to locate our control (how we might help, do good, or be useful) in the world is enough to make us anxious.

Often in these circumstances we're left with few options:

1. BELIEVE earnestly that our individual contribution to the large-scale is working, and that the large-scale (read: individually incomprehensible) thing is pointed in the right direction
2. Panic
3. Identify the things we DO have control over (the things we can help, do good for, or be useful to immediately) and start there
4. Oscillate quickly between the three other options

So here I try: there's a corner of the world I can do mostly unambiguously good within. Plants, friends, direct acts of service, humor, analysis, a listening ear and verbal process in real time, a psychologically safe place to disagree, new frames or depth for conversations that have been flattened by media and social media exposure. If I don't do these things effective action will have failed to leave my body. Even when they do I'll find myself oscillating into panic or self-righteous certainty, but they are greatly diminished. When I have spare time I'll build. The levers and knobs I can interact with to do good in the world are limited in part because they're the levers and knobs I've thus far disclosed. Building capacity will disclose more options.

Humble action within the sphere; humble action on the sphere itself; keep growing; keep going.
