#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: post
title: Sensations of Mono no aware
categories: attempts
---
#+END_EXPORT
** Sensations of Mono no aware
The in-between times are collapsing rapidly. Winter is turning to spring, and summer to fall. 

Tendrils of green poking through the dull brown left behind by feet of snow. Green turning brown as the world battens its hatches for the coming winter.

Grieving the world we thought it would be. Seeing potential in new growth and strength.

The world out there opening up to let the light pour in, the people closing themselves off in preparation for the coming storm.

Long moments stretching longer with rapid changes, the stagnation of yesterday giving way, forcefully, to a today that is radically different from days previous.

This too, a new normal, itself a transition. No matter how used to isolation and self-distraction, this is not the world of tomorrow. Less pointlessness and make-work, maybe. But in all likelihood a more robust world is a harder working world in general. More redundancy. More self-sufficiency. More focus on the unforgiving push-pull with material reality.

Uncertainty rules the transition, and material security rules the uncertainty. The fate of many millions of human lives contingent on forgetting freedoms, on maintaining composure, on keeping infrastructure afloat as even the young and durable crumple under the load. As we find new patterns on the floor of our apartments, government interventions reshape the world outside our doors.

This is a world(big world) of limited permission, a world(our world) of limitless trust and forgiveness. New social contracts, deeper social connections.

Our friends, our family, the people on the block. Is it their spring or their fall? Is it ours? Time undone, time out of time impossible.

Not the same, but it never was, just faster.
