#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_EXPORT html
---
layout: wide
title: Translation
categories: misc
---
#+END_EXPORT

* Translation

One of the things I’ve wondered aloud about on this list is “translation” between various operating levels - upward and downward the ladder of complexity, between different systems of thought that are working at different levels of abstraction, from ideas into praxis, etc. These sort of translations often seem to be implicit and unconscious, partially solved by emergent organizational structures. These structures then become the models for a codification and systematization of scope and responsibilities.

Part of what I find so exciting about metamodern thought is that it tends to explicitly recognize this process. Metamodernists, especially of the developmental ilk, of which there are many on this list, identify and name the many thought frameworks, developmental axes, power structures, and social worlds that need to be translated between. Identifying levels and recognizing the need for translation are the first and second steps, and I’m very curious about the next ones. Given the current niche status of metamodern orgs, it seems prudent to develop translations with broad appeal. I don’t know what that looks like, but here are some other places where levels have been identified and there is active translational work:

    + Medicine has the aptly named Translational Science [[https://en.wikipedia.org/wiki/Translational_research]] , [[https://accelerate.ucsf.edu/about/clinical-and-translational]] that tries to bridge the gaps between lab work and community health. :: Researcher/Theorist -> Researcher/Clinician -> Clinical Practice -> Public Health
    + Aeronautics programs sometimes use a TRL [[https://en.wikipedia.org/wiki/Technology_readiness_level]] that facilitates communication about readiness and provides a common map of what progress looks like across orgs. :: Researcher/Theorist -> Researcher/Developer -> Engineer -> Manufacturers -> Ready Technology
    + Patreon(lol) very recently published an “Engineering Levels” guide [[https://levels.patreon.com/]], that describes the progression of scope and concerns of an engineer as they develop. :: IC6 (Architecture / Vision / Multi-metasystem meta-pattern decisions) -> IC5 (meta-pattern decision making) -> IC4 (multi-system decision making) -> IC3 (single system decision making) -> IC2 (contributing) -> IC1 (learning)
    + Business/Management has a ton of stuff, but [[https://en.wikipedia.org/wiki/Six_Thinking_Hats]] is an example of trying to balance the needs of a few (very basic) analytical frameworks. Notably this translation is horizontal, not vertical, except that “blue hat” is in control. More like translating between languages or equal paradigms. :: 
    + Reasoning about higher mathematical dimensions feels isomorphic to this sort of translation [[https://www.youtube.com/watch?v=zwAD6dRSVyI]] :: Multi-dimensional object -> 3D projection -> 2D projection of 3D object for viewing on a computer screen
    + Simple english wikipedia has done a ton of work translating between large and small vocabularies [[https://simple.wikipedia.org/wiki/Post-postmodernism]] which honestly is a good place to start :: 

So I dunno. That’s what I have. Thoughts? Is it self-evident that this process is necessary? Is there a there there? Are we actively developing a metamodern translational science? Are there examples of it? Does this mailing list count? Are there other examples like the ones I listed that are interesting attempts elsewhere? Alter Ego?

If this is worthwhile I may try to write up more.

/Taken from a mailing list message dating 2018-04-19./
